# Generated by Django 5.2.17 on 2026-08-17 22:32

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('instructors', '0001_initial'),
        ('lessons', '0001_initial'),
        ('locations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Generated automatically (CAMP001) when left blank.', max_length=20, unique=True, verbose_name='camp code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='surf_camps/%Y/%m/', validators=[apps.core.validators.validate_image_upload], verbose_name='photo')),
                ('start_date', models.DateField(db_index=True, verbose_name='start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='end date')),
                ('capacity', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacity')),
                ('min_participants', models.PositiveIntegerField(default=1, help_text='Below this number the camp is not economically viable.', verbose_name='minimum participants')),
                ('min_level', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], db_index=True, default='first_time', max_length=20, verbose_name='minimum level')),
                ('max_level', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], db_index=True, default='advanced', max_length=20, verbose_name='maximum level')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='price per person')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='deposit')),
                ('single_room_supplement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='single room supplement')),
                ('includes_accommodation', models.BooleanField(default=True, verbose_name='accommodation included')),
                ('includes_meals', models.BooleanField(default=True, verbose_name='meals included')),
                ('includes_transfer', models.BooleanField(default=False, verbose_name='airport transfer included')),
                ('includes_equipment', models.BooleanField(default=True, verbose_name='equipment included')),
                ('includes_insurance', models.BooleanField(default=False, verbose_name='insurance included')),
                ('accommodation_name', models.CharField(blank=True, max_length=200, verbose_name='accommodation')),
                ('accommodation_address', models.TextField(blank=True, verbose_name='accommodation address')),
                ('meal_plan', models.TextField(blank=True, help_text='For example: breakfast + lunch, 7 days.', verbose_name='meal plan')),
                ('transfer_pickup_point', models.CharField(blank=True, max_length=200, verbose_name='pick-up point')),
                ('transfer_notes', models.TextField(blank=True, verbose_name='transfer notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('full', 'Fully booked'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('instructors', models.ManyToManyField(blank=True, related_name='camps', to='instructors.instructor', verbose_name='instructors')),
                ('lead_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_camps', to='instructors.instructor', verbose_name='lead instructor')),
                ('spot', models.ForeignKey(help_text='Default spot. Each camp day may override it as the forecast changes.', on_delete=django.db.models.deletion.PROTECT, related_name='surf_camps', to='locations.surfspot', verbose_name='home surf spot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'surf camp',
                'verbose_name_plural': 'surf camps',
                'ordering': ['-start_date', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CampParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='room number')),
                ('room_type', models.CharField(choices=[('single', 'Single room'), ('double', 'Double room'), ('shared', 'Shared room / dorm')], default='shared', max_length=10, verbose_name='room type')),
                ('roommate_preference', models.CharField(blank=True, max_length=200, verbose_name='roommate preference')),
                ('arrival_datetime', models.DateTimeField(blank=True, null=True, verbose_name='arrival')),
                ('departure_datetime', models.DateTimeField(blank=True, null=True, verbose_name='departure')),
                ('arrival_flight', models.CharField(blank=True, max_length=40, verbose_name='arrival flight')),
                ('departure_flight', models.CharField(blank=True, max_length=40, verbose_name='departure flight')),
                ('needs_transfer', models.BooleanField(db_index=True, default=False, verbose_name='needs transfer')),
                ('dietary_requirements', models.CharField(blank=True, max_length=200, verbose_name='dietary requirements')),
                ('medical_notes', models.TextField(blank=True, help_text='Visible to instructors and lifeguards on the daily roster.', verbose_name='medical notes')),
                ('t_shirt_size', models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=5, verbose_name='t-shirt size')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total collected for this place; mirrors the payments in Finance.', max_digits=12, verbose_name='amount paid')),
                ('deposit_paid', models.BooleanField(default=False, verbose_name='deposit paid')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('departed', 'Departed'), ('cancelled', 'Cancelled')], db_index=True, default='registered', max_length=20, verbose_name='status')),
                ('cancellation_reason', models.CharField(blank=True, max_length=200, verbose_name='cancellation reason')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camp_participations', to='bookings.booking', verbose_name='booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camp_participations', to='students.student', verbose_name='student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='surf_camps.surfcamp', verbose_name='camp')),
            ],
            options={
                'verbose_name': 'camp participant',
                'verbose_name_plural': 'camp participants',
                'ordering': ['camp', 'student'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CampDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('day_number', models.PositiveIntegerField(default=1, verbose_name='day number')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('weather_note', models.TextField(blank=True, verbose_name='weather note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('spot', models.ForeignKey(blank=True, help_text="Leave empty to use the camp's home spot.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camp_days', to='locations.surfspot', verbose_name='spot for the day')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='surf_camps.surfcamp', verbose_name='camp')),
            ],
            options={
                'verbose_name': 'camp day',
                'verbose_name_plural': 'camp days',
                'ordering': ['date'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CampActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('activity_type', models.CharField(choices=[('surf_lesson', 'Surf lesson'), ('theory', 'Theory session'), ('video_analysis', 'Video analysis'), ('yoga', 'Yoga'), ('fitness', 'Fitness / warm-up'), ('excursion', 'Excursion'), ('meal', 'Meal'), ('free_time', 'Free time'), ('transfer', 'Transfer'), ('social', 'Social event'), ('other', 'Other')], db_index=True, default='other', max_length=20, verbose_name='type')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='location')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camp_activities', to='instructors.instructor', verbose_name='instructor')),
                ('lesson', models.ForeignKey(blank=True, help_text='Set when this activity is a lesson scheduled in the lessons module.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camp_activities', to='lessons.lesson', verbose_name='linked lesson')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('camp_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='surf_camps.campday', verbose_name='camp day')),
            ],
            options={
                'verbose_name': 'camp activity',
                'verbose_name_plural': 'camp activities',
                'ordering': ['start_time', 'id'],
                'indexes': [models.Index(fields=['camp_day', 'start_time'], name='surf_camps__camp_da_c6772a_idx'), models.Index(fields=['activity_type'], name='surf_camps__activit_d05e02_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='camp_activity_end_after_start')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='surfcamp',
            index=models.Index(fields=['status', 'start_date'], name='surf_camps__status_5c32f9_idx'),
        ),
        migrations.AddIndex(
            model_name='surfcamp',
            index=models.Index(fields=['start_date', 'end_date'], name='surf_camps__start_d_a6f116_idx'),
        ),
        migrations.AddIndex(
            model_name='surfcamp',
            index=models.Index(fields=['is_active', 'status'], name='surf_camps__is_acti_499391_idx'),
        ),
        migrations.AddConstraint(
            model_name='surfcamp',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='surf_camp_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='surfcamp',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='surf_camp_capacity_positive'),
        ),
        migrations.AddIndex(
            model_name='campparticipant',
            index=models.Index(fields=['camp', 'status'], name='surf_camps__camp_id_83d162_idx'),
        ),
        migrations.AddIndex(
            model_name='campparticipant',
            index=models.Index(fields=['status', 'needs_transfer'], name='surf_camps__status_a4eba5_idx'),
        ),
        migrations.AddConstraint(
            model_name='campparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('camp', 'student'), name='unique_active_participant_per_camp'),
        ),
        migrations.AddIndex(
            model_name='campday',
            index=models.Index(fields=['camp', 'date'], name='surf_camps__camp_id_69cb7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='campday',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('camp', 'date'), name='unique_active_day_per_camp'),
        ),
    ]
