# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('goal', models.TextField(blank=True, help_text='What the operator asked the agent to achieve.', verbose_name='goal')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'terminal session',
                'verbose_name_plural': 'terminal sessions',
                'ordering': ['-updated_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CodeChangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('file_path', models.CharField(max_length=500, verbose_name='file')),
                ('change_type', models.CharField(choices=[('create', 'Create file'), ('modify', 'Modify file'), ('delete', 'Delete file')], default='modify', max_length=10, verbose_name='change type')),
                ('original_content', models.TextField(blank=True, verbose_name='original content')),
                ('proposed_content', models.TextField(blank=True, verbose_name='proposed content')),
                ('unified_diff', models.TextField(blank=True, verbose_name='diff')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('reverted', 'Reverted'), ('failed', 'Failed to apply')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('apply_error', models.CharField(blank=True, max_length=500)),
                ('checkpoint_branch', models.CharField(blank=True, max_length=200, verbose_name='checkpoint branch')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_proposals_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='ai_terminal.terminalsession')),
            ],
            options={
                'verbose_name': 'code change proposal',
                'verbose_name_plural': 'code change proposals',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TerminalCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('origin', models.CharField(choices=[('user', 'Typed by a user'), ('agent', 'Proposed by the AI agent')], default='user', max_length=8, verbose_name='origin')),
                ('command', models.TextField(verbose_name='command')),
                ('argv', models.JSONField(blank=True, default=list, verbose_name='argument vector')),
                ('rationale', models.TextField(blank=True, help_text='Why the agent wants to run this.', verbose_name='rationale')),
                ('risk', models.CharField(default='blocked', max_length=20, verbose_name='risk')),
                ('policy_rule', models.CharField(blank=True, max_length=100, verbose_name='matched policy rule')),
                ('policy_reason', models.CharField(blank=True, max_length=500, verbose_name='policy reason')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked by policy'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('timed_out', 'Timed out'), ('cancelled', 'Cancelled')], db_index=True, default='proposed', max_length=20, verbose_name='status')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('decision_note', models.CharField(blank=True, max_length=500, verbose_name='decision note')),
                ('edited_command', models.TextField(blank=True, verbose_name='edited command')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='exit code')),
                ('stdout', models.TextField(blank=True, verbose_name='standard output')),
                ('stderr', models.TextField(blank=True, verbose_name='standard error')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='duration (ms)')),
                ('output_truncated', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='executed at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_commands_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_commands_requested', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='ai_terminal.terminalsession')),
            ],
            options={
                'verbose_name': 'terminal command',
                'verbose_name_plural': 'terminal commands',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='ai_terminal_session_de540e_idx')],
            },
        ),
    ]
