# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('customers', '0001_initial'),
        ('equipment', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('rental_code', models.CharField(db_index=True, help_text='Assigned automatically, e.g. RNT00001.', max_length=20, unique=True, verbose_name='rental code')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Out with customer'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('lost', 'Not returned / lost')], db_index=True, default='reserved', max_length=12, verbose_name='status')),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], db_index=True, default='daily', max_length=10, verbose_name='period')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='starts at')),
                ('expected_return_at', models.DateTimeField(db_index=True, verbose_name='due back')),
                ('returned_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='returned at')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash or card pre-authorisation held against damage and late return.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='deposit taken')),
                ('deposit_returned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually handed back at check-in.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='deposit returned')),
                ('deposit_status', models.CharField(choices=[('held', 'Held'), ('returned', 'Returned to customer'), ('forfeited', 'Withheld')], db_index=True, default='held', max_length=10, verbose_name='deposit status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='hire charge')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='discount')),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='late fee')),
                ('damage_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='damage charge')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='paid')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('overdue', 'Overdue')], db_index=True, default='unpaid', max_length=10, verbose_name='payment status')),
                ('id_document_held', models.BooleanField(default=False, help_text='An ID is retained at the counter until the gear comes back.', verbose_name='identity document held')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('booking', models.ForeignKey(blank=True, help_text='Links a hire to the lesson or camp booking it belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='bookings.booking', verbose_name='booking')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals_checked_in', to=settings.AUTH_USER_MODEL, verbose_name='checked in by')),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals_checked_out', to=settings.AUTH_USER_MODEL, verbose_name='checked out by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(help_text='The person who signs for the equipment and owes the money.', on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='customers.customer', verbose_name='customer')),
                ('student', models.ForeignKey(blank=True, help_text='Set when the gear is used by a student other than the payer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='students.student', verbose_name='student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'rental',
                'verbose_name_plural': 'rentals',
                'ordering': ['-start_at', '-id'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price of one unit for the whole hire period, as agreed at check-out.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='unit price')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='line total')),
                ('condition_out', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unusable', 'Unusable')], default='good', max_length=12, verbose_name='condition out')),
                ('condition_in', models.CharField(blank=True, choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unusable', 'Unusable')], max_length=12, null=True, verbose_name='condition in')),
                ('damage_reported', models.BooleanField(db_index=True, default=False, verbose_name='damage reported')),
                ('damage_type', models.CharField(blank=True, choices=[('ding', 'Ding'), ('crack', 'Crack'), ('fin_damage', 'Fin damage'), ('leash_damage', 'Leash damage'), ('wetsuit_tear', 'Wetsuit tear'), ('zipper', 'Zipper failure'), ('water_damage', 'Water damage / delamination'), ('delamination', 'Delamination'), ('snapped', 'Snapped board'), ('general', 'General maintenance'), ('other', 'Other')], max_length=20, verbose_name='damage type')),
                ('damage_notes', models.TextField(blank=True, verbose_name='damage notes')),
                ('damage_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='damage charge')),
                ('returned_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='returned at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_items', to='equipment.equipment', verbose_name='equipment')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.rental', verbose_name='rental')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'rental item',
                'verbose_name_plural': 'rental items',
                'ordering': ['rental_id', 'id'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['status', 'expected_return_at'], name='rentals_ren_status_817986_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['customer', '-start_at'], name='rentals_ren_custome_1d48f8_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['payment_status', '-start_at'], name='rentals_ren_payment_f59b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalitem',
            index=models.Index(fields=['equipment', 'returned_at'], name='rentals_ren_equipme_463a5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentalitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('rental', 'equipment'), name='rentals_unique_equipment_per_rental'),
        ),
    ]
