# Generated by Django 5.2.17 on 2026-08-17 22:32

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='address line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state / region')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2, verbose_name='country')),
                ('customer_code', models.CharField(blank=True, db_index=True, help_text='Generated automatically, e.g. CUS00001.', max_length=20, unique=True, verbose_name='customer code')),
                ('first_name', models.CharField(max_length=80, verbose_name='first name')),
                ('last_name', models.CharField(max_length=80, verbose_name='last name')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='Stored in international form, e.g. +905551234567.', max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +90 555 123 45 67.', regex='^\\+?[0-9 ()\\-]{6,25}$')], verbose_name='phone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/photos/%Y/%m/', validators=[apps.core.validators.validate_image_upload], verbose_name='photo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], max_length=12, verbose_name='gender')),
                ('nationality', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2, e.g. TR', max_length=2, verbose_name='nationality')),
                ('preferred_language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('ru', 'Русский'), ('ar', 'العربية')], default='en', max_length=5, verbose_name='preferred language')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120, verbose_name='emergency contact')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +90 555 123 45 67.', regex='^\\+?[0-9 ()\\-]{6,25}$')], verbose_name='emergency contact phone')),
                ('emergency_contact_relation', models.CharField(blank=True, help_text='e.g. Mother, Partner, Friend', max_length=60, verbose_name='relationship')),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('phone', 'Phone'), ('email', 'E-mail'), ('website', 'Website'), ('partner', 'Partner / agency'), ('social', 'Social media'), ('returning', 'Returning customer'), ('other', 'Other')], db_index=True, default='walk_in', max_length=16, verbose_name='source')),
                ('marketing_consent', models.BooleanField(default=False, help_text='Explicit opt-in for campaigns. Without it we never contact them.', verbose_name='marketing consent')),
                ('marketing_consent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='consent given at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('first_visit_date', models.DateField(blank=True, null=True, verbose_name='first visit')),
                ('last_visit_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='last visit')),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='lifetime value')),
                ('total_bookings', models.PositiveIntegerField(default=0, verbose_name='total bookings')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.OneToOneField(blank=True, help_text='Linked when the customer is given access to the portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='login account')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['last_name', 'first_name'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_tag_links', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='customers.customer', verbose_name='customer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to='core.tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'customer tag',
                'verbose_name_plural': 'customer tags',
                'ordering': ['tag__name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='customers', through='customers.CustomerTag', to='core.tag', verbose_name='tags'),
        ),
        migrations.AddIndex(
            model_name='customertag',
            index=models.Index(fields=['tag', 'customer'], name='customers_c_tag_id_f27f09_idx'),
        ),
        migrations.AddConstraint(
            model_name='customertag',
            constraint=models.UniqueConstraint(fields=('customer', 'tag'), name='customers_customertag_unique'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='customers_c_last_na_27dbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active', 'source'], name='customers_c_is_acti_a05fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email', 'is_deleted'], name='customers_c_email_a85101_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone', 'last_name'], name='customers_c_phone_19ee99_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-last_visit_date'], name='customers_c_last_vi_9af6e6_idx'),
        ),
    ]
