# Generated by Django 5.2.17 on 2026-08-17 22:32

import apps.accounts.models
import apps.core.validators
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail address')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('operations_manager', 'Operations Manager'), ('head_instructor', 'Head Instructor'), ('surf_instructor', 'Surf Instructor'), ('lifeguard', 'Lifeguard'), ('reception', 'Reception'), ('rental_staff', 'Rental Staff'), ('equipment_manager', 'Equipment Manager'), ('maintenance_staff', 'Maintenance Staff'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('photographer', 'Photographer'), ('customer', 'Customer'), ('student', 'Student')], db_index=True, default='reception', max_length=32, verbose_name='role')),
                ('phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +90 555 123 45 67.', regex='^\\+?[0-9 ()\\-]{6,25}$')], verbose_name='phone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/%Y/', validators=[apps.core.validators.validate_image_upload], verbose_name='photo')),
                ('employee_id', models.CharField(blank=True, max_length=30, verbose_name='employee ID')),
                ('language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], default='tr', max_length=5, verbose_name='interface language')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='job title')),
                ('extra_capabilities', models.JSONField(blank=True, default=list, verbose_name='extra capabilities')),
                ('denied_capabilities', models.JSONField(blank=True, default=list, verbose_name='denied capabilities')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='must change password')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='last seen')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['first_name', 'last_name', 'username'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='requested from')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'password reset request',
                'verbose_name_plural': 'password reset requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='session key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='user agent')),
                ('login_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='login at')),
                ('logout_at', models.DateTimeField(blank=True, null=True, verbose_name='logout at')),
                ('was_successful', models.BooleanField(default=True, verbose_name='successful')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user session',
                'verbose_name_plural': 'user sessions',
                'ordering': ['-login_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
    ]
