# Generated by Django 5.2.17 on 2026-08-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bootstrap_account',
            field=models.BooleanField(default=False, verbose_name='first-run bootstrap account'),
        ),
    ]
