# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='name')),
                ('code', models.SlugField(help_text='Stable identifier used by the API and the scheduler.', max_length=60, unique=True, verbose_name='code')),
                ('report_key', models.CharField(db_index=True, help_text='Key of the builder in the report catalogue, e.g. daily_operations.', max_length=60, verbose_name='report')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='default format')),
                ('default_filters', models.JSONField(blank=True, default=dict, help_text='Filter values applied when this report is run, e.g. {"range": "30"}.', verbose_name='default filters')),
                ('required_capability', models.CharField(blank=True, help_text='Capability a user must hold to run this report. Left blank it falls back to the capability declared by the report itself.', max_length=60, verbose_name='required capability')),
                ('is_scheduled', models.BooleanField(db_index=True, default=False, help_text='Requires a schedule expression and at least one recipient.', verbose_name='run on a schedule')),
                ('schedule_cron', models.CharField(blank=True, help_text='Five-field cron expression: minute hour day month weekday, e.g. "0 7 * * 1".', max_length=100, verbose_name='schedule')),
                ('recipients', models.JSONField(blank=True, default=list, help_text='E-mail addresses the generated file is sent to.', verbose_name='recipients')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='last run at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'report definition',
                'verbose_name_plural': 'report definitions',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('report_key', models.CharField(db_index=True, max_length=60, verbose_name='report')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='format')),
                ('filters_used', models.JSONField(blank=True, default=dict, verbose_name='filters used')),
                ('file', models.FileField(blank=True, upload_to='reports/%Y/%m/', verbose_name='file')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='file size (bytes)')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='rows')),
                ('generation_ms', models.PositiveIntegerField(default=0, help_text='Wall-clock time spent querying and rendering.', verbose_name='generation time (ms)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='generated by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('definition', models.ForeignKey(blank=True, help_text='Set when the export came from a saved configuration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reporting.reportdefinition', verbose_name='definition')),
            ],
            options={
                'verbose_name': 'generated report',
                'verbose_name_plural': 'generated reports',
                'ordering': ['-created_at', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['report_key', 'is_active'], name='reporting_r_report__34dcef_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['is_scheduled', 'is_active'], name='reporting_r_is_sche_24e2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['-created_at'], name='reporting_g_created_3d115d_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['report_key', '-created_at'], name='reporting_g_report__89be37_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['status', '-created_at'], name='reporting_g_status_2de6f1_idx'),
        ),
    ]
