# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('backup_code', models.CharField(db_index=True, help_text='Reference such as BKP-20260815-001. Typed by hand to confirm a restore.', max_length=32, unique=True, verbose_name='backup code')),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily (scheduled)'), ('weekly', 'Weekly (scheduled)'), ('monthly', 'Monthly (scheduled)'), ('pre_restore', 'Safety copy before a restore')], db_index=True, default='manual', max_length=16, verbose_name='type')),
                ('scope', models.CharField(choices=[('database', 'Database only'), ('media', 'Uploaded files only'), ('full', 'Full — database, files and configuration manifest'), ('config', 'Configuration manifest only')], db_index=True, default='full', max_length=16, verbose_name='scope')),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('corrupt', 'Corrupt — do not restore')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('file_path', models.CharField(blank=True, help_text='Absolute path of the artefact on the backup volume.', max_length=500, verbose_name='file path')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='size (bytes)')),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, help_text='Recomputed on every verification. A mismatch means the file changed.', max_length=64, verbose_name='SHA-256 checksum')),
                ('database_engine', models.CharField(blank=True, help_text='A PostgreSQL dump cannot be restored into SQLite, or the reverse.', max_length=100, verbose_name='database engine')),
                ('django_version', models.CharField(blank=True, max_length=20, verbose_name='Django version')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name='application version')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='duration (ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='error')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Set when the checksum and an engine-level integrity check both passed.', verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'backup',
                'verbose_name_plural': 'backups',
                'ordering': ['-created_at', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RestoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('verifying', 'Verifying the backup'), ('running', 'Restoring'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Failed — rolled back to the safety copy')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='duration (ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='error')),
                ('confirmation_text', models.CharField(blank=True, help_text='What the operator typed. Must match the backup code exactly.', max_length=64, verbose_name='typed confirmation')),
                ('pre_restore_checks', models.JSONField(blank=True, default=dict, help_text='Ordered result of every gate the restore had to pass.', verbose_name='pre-restore checks')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restores', to='backups.backuprecord', verbose_name='backup')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_restores_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='confirmed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('safety_backup', models.ForeignKey(blank=True, help_text='Taken automatically immediately before the restore began.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protected_restores', to='backups.backuprecord', verbose_name='safety copy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'restore',
                'verbose_name_plural': 'restores',
                'ordering': ['-created_at', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['-created_at'], name='backups_bac_created_8cd42a_idx'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['status', '-created_at'], name='backups_bac_status_982c49_idx'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['backup_type', '-created_at'], name='backups_bac_backup__29fb67_idx'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['scope', 'status'], name='backups_bac_scope_59e549_idx'),
        ),
        migrations.AddIndex(
            model_name='restorerecord',
            index=models.Index(fields=['-created_at'], name='backups_res_created_372c63_idx'),
        ),
        migrations.AddIndex(
            model_name='restorerecord',
            index=models.Index(fields=['status', '-created_at'], name='backups_res_status_fc7efe_idx'),
        ),
    ]
