# Generated by Django 5.2.17 on 2026-08-17 22:32

import apps.core.validators
import apps.finance.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('purchased_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='purchased on')),
                ('expires_on', models.DateField(db_index=True, verbose_name='expires on')),
                ('lessons_total', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='lessons included')),
                ('lessons_used', models.PositiveSmallIntegerField(default=0, verbose_name='lessons used')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='amount paid')),
                ('status', models.CharField(choices=[('active', 'Active'), ('exhausted', 'Fully used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=10, verbose_name='status')),
            ],
            options={
                'verbose_name': 'customer package',
                'verbose_name_plural': 'customer packages',
                'ordering': ['-purchased_on', '-id'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('expense_code', models.CharField(blank=True, db_index=True, help_text='Allocated automatically, e.g. EXP00001.', max_length=20, unique=True, verbose_name='expense code')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='tax')),
                ('spent_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='spent on')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='supplier')),
                ('invoice_reference', models.CharField(blank=True, max_length=100, verbose_name='supplier invoice no.')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='finance/receipts/%Y/%m/', validators=[apps.core.validators.validate_document_upload], verbose_name='receipt')),
                ('is_recurring', models.BooleanField(db_index=True, default=False, verbose_name='recurring')),
                ('recurrence_months', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='repeats every (months)')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'ordering': ['-spent_on', '-id'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'expense category',
                'verbose_name_plural': 'expense categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('invoice_number', models.CharField(blank=True, db_index=True, help_text='Allocated automatically per year, e.g. INV-2026-00001.', max_length=20, unique=True, verbose_name='invoice number')),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='issue date')),
                ('due_date', models.DateField(db_index=True, verbose_name='due date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=10, verbose_name='status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='discount')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT percentage applied after the discount.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='tax rate %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='tax')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='paid')),
                ('currency', models.CharField(default=apps.finance.models.default_currency, max_length=3, verbose_name='currency')),
                ('notes', models.TextField(blank=True, help_text='Printed on the invoice.', verbose_name='notes')),
                ('terms', models.TextField(blank=True, verbose_name='payment terms')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-issue_date', '-id'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='unit price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='line discount')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='line total')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'invoice line',
                'verbose_name_plural': 'invoice lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('payment_code', models.CharField(blank=True, db_index=True, help_text='Allocated automatically, e.g. PAY00001.', max_length=20, unique=True, verbose_name='payment code')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='amount')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit / debit card'), ('transfer', 'Bank transfer'), ('online', 'Online payment'), ('package', 'Lesson package'), ('voucher', 'Voucher'), ('other', 'Other')], db_index=True, default='cash', max_length=12, verbose_name='method')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('overdue', 'Overdue')], db_index=True, default='paid', max_length=10, verbose_name='status')),
                ('category', models.CharField(choices=[('lesson', 'Lesson'), ('camp', 'Surf camp'), ('rental', 'Equipment rental'), ('shop', 'Shop'), ('package', 'Lesson package'), ('deposit', 'Deposit'), ('other', 'Other')], db_index=True, default='other', help_text='What the money was for. Drives the revenue breakdown.', max_length=10, verbose_name='category')),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='paid at')),
                ('reference', models.CharField(blank=True, help_text='Card authorisation, transfer reference or receipt number.', max_length=100, verbose_name='reference')),
                ('is_refund', models.BooleanField(db_index=True, default=False, verbose_name='refund')),
                ('refund_reason', models.TextField(blank=True, verbose_name='refund reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-paid_at', '-id'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PricePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('lesson_count', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='lessons included')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price')),
                ('validity_days', models.PositiveSmallIntegerField(default=180, help_text='Counted from the day the package is sold.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='valid for (days)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'price package',
                'verbose_name_plural': 'price packages',
                'ordering': ['sort_order', 'name'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('period_start', models.DateField(db_index=True, verbose_name='period start')),
                ('period_end', models.DateField(db_index=True, verbose_name='period end')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='base amount')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='commission %')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='commission')),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10, verbose_name='status')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='paid at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='instructors.instructor', verbose_name='instructor')),
            ],
            options={
                'verbose_name': 'commission record',
                'verbose_name_plural': 'commission records',
                'ordering': ['-period_end', '-id'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
