# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('customers', '0001_initial'),
        ('finance', '0002_initial'),
        ('lessons', '0001_initial'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='rentals.rental', verbose_name='rental'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice', verbose_name='invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bookings.booking', verbose_name='booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.invoice', verbose_name='invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payments_received', to=settings.AUTH_USER_MODEL, verbose_name='received by'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='finance.payment', verbose_name='refund of'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='rentals.rental', verbose_name='rental'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='pricepackage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='pricepackage',
            name='lesson_type',
            field=models.ForeignKey(blank=True, help_text='Used to work out the saving against buying lessons singly.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_packages', to='lessons.lessontype', verbose_name='lesson type'),
        ),
        migrations.AddField(
            model_name='pricepackage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='customerpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_packages', to='finance.pricepackage', verbose_name='package'),
        ),
        migrations.AddIndex(
            model_name='commissionrecord',
            index=models.Index(fields=['instructor', 'status'], name='finance_com_instruc_9ace19_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrecord',
            index=models.Index(fields=['status', 'period_end'], name='finance_com_status_89c88c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'spent_on'], name='finance_exp_categor_a68c21_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['spent_on', 'is_recurring'], name='finance_exp_spent_o_2ef752_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='finance_inv_status_0e2dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='finance_inv_custome_f7b372_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date', 'status'], name='finance_inv_issue_d_9d1ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'sort_order'], name='finance_inv_invoice_90f94c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['category', 'paid_at'], name='finance_pay_categor_0a239b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', '-paid_at'], name='finance_pay_custome_187d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'paid_at'], name='finance_pay_method_cd08a4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_refund', 'paid_at'], name='finance_pay_is_refu_ba77c6_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpackage',
            index=models.Index(fields=['customer', 'status'], name='finance_cus_custome_e440ab_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpackage',
            index=models.Index(fields=['status', 'expires_on'], name='finance_cus_status_95b17e_idx'),
        ),
    ]
