# Generated by Django 5.2.17 on 2026-08-17 22:32

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('instructor_code', models.CharField(blank=True, db_index=True, help_text='Generated automatically, e.g. INS0001.', max_length=20, unique=True, verbose_name='instructor code')),
                ('bio', models.TextField(blank=True, help_text='Shown on the public profile and on lesson confirmations.', verbose_name='biography')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/photos/%Y/', validators=[apps.core.validators.validate_image_upload], verbose_name='photo')),
                ('specialties', models.JSONField(blank=True, default=list, help_text='Free-form list, e.g. longboard, kids, competition coaching.', verbose_name='specialties')),
                ('languages', models.JSONField(blank=True, default=list, help_text='ISO 639-1 codes, e.g. tr, en, de.', verbose_name='languages spoken')),
                ('max_level_taught', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], db_index=True, default='beginner', max_length=20, verbose_name='highest level taught')),
                ('max_students_per_lesson', models.PositiveSmallIntegerField(default=8, help_text="Personal ceiling. The effective limit is the lower of this value and the safety ratio for the group's level.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='maximum students per lesson')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='hourly rate')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='commission %')),
                ('hire_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='hire date')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive instructors keep their history but cannot be assigned.', verbose_name='active')),
                ('is_available_for_booking', models.BooleanField(db_index=True, default=True, help_text='Turn off to keep an active instructor out of the booking pool.', verbose_name='open for bookings')),
                ('rating_average', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='average rating')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='ratings received')),
                ('total_lessons_taught', models.PositiveIntegerField(default=0, verbose_name='lessons taught')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, verbose_name='emergency contact name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +90 555 123 45 67.', regex='^\\+?[0-9 ()\\-]{6,25}$')], verbose_name='emergency contact phone')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.OneToOneField(help_text='The login this instructor uses. One profile per account.', on_delete=django.db.models.deletion.PROTECT, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='user account')),
            ],
            options={
                'verbose_name': 'instructor',
                'verbose_name_plural': 'instructors',
                'ordering': ['user__first_name', 'user__last_name', 'instructor_code'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('kind', models.CharField(choices=[('isa_l1', 'ISA Surf Level 1 Instructor'), ('isa_l2', 'ISA Surf Level 2 Coach'), ('surfing_england', 'Surfing England coaching award'), ('lifeguard', 'Surf lifeguard / water safety'), ('first_aid', 'First aid'), ('cpr', 'CPR'), ('safeguarding', 'Safeguarding'), ('powerboat', 'Powerboat / rescue craft'), ('other', 'Other')], db_index=True, default='other', max_length=20, verbose_name='type')),
                ('name', models.CharField(help_text='Exact title printed on the certificate.', max_length=200, verbose_name='name')),
                ('issuing_body', models.CharField(blank=True, max_length=150, verbose_name='issuing body')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='certificate number')),
                ('issued_on', models.DateField(verbose_name='issued on')),
                ('expires_on', models.DateField(blank=True, db_index=True, help_text='Leave empty for a credential that does not expire.', null=True, verbose_name='expires on')),
                ('document', models.FileField(blank=True, null=True, upload_to='instructors/certifications/%Y/%m/', validators=[apps.core.validators.validate_document_upload], verbose_name='evidence')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='A named staff member has seen the original certificate.', verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certifications', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='instructors.instructor', verbose_name='instructor')),
            ],
            options={
                'verbose_name': 'certification',
                'verbose_name_plural': 'certifications',
                'ordering': [models.OrderBy(models.F('expires_on'), nulls_last=True), 'kind'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True, verbose_name='weekday')),
                ('start_time', models.TimeField(verbose_name='from')),
                ('end_time', models.TimeField(verbose_name='to')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('valid_from', models.DateField(blank=True, help_text='Leave empty for a pattern that has always applied.', null=True, verbose_name='valid from')),
                ('valid_until', models.DateField(blank=True, help_text='Leave empty for a pattern with no end date.', null=True, verbose_name='valid until')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='instructors.instructor', verbose_name='instructor')),
            ],
            options={
                'verbose_name': 'availability slot',
                'verbose_name_plural': 'availability slots',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('period_start', models.DateField(verbose_name='period from')),
                ('period_end', models.DateField(verbose_name='period to')),
                ('teaching_quality', models.PositiveSmallIntegerField(choices=[(1, '1 — Needs immediate attention'), (2, '2 — Below expectations'), (3, '3 — Meets expectations'), (4, '4 — Above expectations'), (5, '5 — Outstanding')], default=3, verbose_name='teaching quality')),
                ('punctuality', models.PositiveSmallIntegerField(choices=[(1, '1 — Needs immediate attention'), (2, '2 — Below expectations'), (3, '3 — Meets expectations'), (4, '4 — Above expectations'), (5, '5 — Outstanding')], default=3, verbose_name='punctuality')),
                ('safety', models.PositiveSmallIntegerField(choices=[(1, '1 — Needs immediate attention'), (2, '2 — Below expectations'), (3, '3 — Meets expectations'), (4, '4 — Above expectations'), (5, '5 — Outstanding')], default=3, verbose_name='safety awareness')),
                ('communication', models.PositiveSmallIntegerField(choices=[(1, '1 — Needs immediate attention'), (2, '2 — Below expectations'), (3, '3 — Meets expectations'), (4, '4 — Above expectations'), (5, '5 — Outstanding')], default=3, verbose_name='communication')),
                ('teamwork', models.PositiveSmallIntegerField(choices=[(1, '1 — Needs immediate attention'), (2, '2 — Below expectations'), (3, '3 — Meets expectations'), (4, '4 — Above expectations'), (5, '5 — Outstanding')], default=3, verbose_name='teamwork')),
                ('strengths', models.TextField(blank=True, verbose_name='strengths')),
                ('improvements', models.TextField(blank=True, verbose_name='areas to improve')),
                ('goals', models.TextField(blank=True, verbose_name='goals for next period')),
                ('overall_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=3, verbose_name='overall score')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='instructors.instructor', verbose_name='instructor')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'performance review',
                'verbose_name_plural': 'performance reviews',
                'ordering': ['-period_end', '-created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('start_date', models.DateField(db_index=True, verbose_name='from')),
                ('end_date', models.DateField(db_index=True, verbose_name='to')),
                ('reason', models.CharField(choices=[('holiday', 'Holiday'), ('sick', 'Sick leave'), ('training', 'Training / course'), ('personal', 'Personal'), ('other', 'Other')], db_index=True, default='holiday', max_length=20, verbose_name='reason')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Only approved absence removes an instructor from the booking pool.', verbose_name='approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_off_periods', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_periods', to='instructors.instructor', verbose_name='instructor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'time off',
                'verbose_name_plural': 'time off',
                'ordering': ['-start_date'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['is_active', 'is_available_for_booking'], name='instructors_is_acti_96fe0d_idx'),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['max_level_taught', 'is_active'], name='instructors_max_lev_ef1508_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['instructor', 'kind'], name='instructors_instruc_b0cbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['expires_on', 'is_verified'], name='instructors_expires_b6756c_idx'),
        ),
        migrations.AddConstraint(
            model_name='certification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('certificate_number', ''), _negated=True)), fields=('instructor', 'kind', 'certificate_number'), name='uniq_certificate_number_per_instructor_kind'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['instructor', 'weekday', 'is_active'], name='instructors_instruc_93038a_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(fields=('instructor', 'weekday', 'start_time'), name='uniq_availability_slot_start'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['instructor', 'period_end'], name='instructors_instruc_a47651_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoff',
            index=models.Index(fields=['instructor', 'start_date', 'end_date'], name='instructors_instruc_25daab_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoff',
            index=models.Index(fields=['is_approved', 'start_date'], name='instructors_is_appr_e1e1e0_idx'),
        ),
    ]
