# Generated by Django 5.2.17 on 2026-08-17 22:32

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('code', models.SlugField(help_text='Stable identifier, e.g. first-student.', max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Use 2–50 letters, digits, hyphens or underscores.', regex='^[A-Za-z0-9][A-Za-z0-9_\\-]{1,49}$')], verbose_name='code')),
                ('title_en', models.CharField(max_length=200, verbose_name='title (EN)')),
                ('title_tr', models.CharField(max_length=200, verbose_name='title (TR)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (EN)')),
                ('description_tr', models.TextField(blank=True, verbose_name='description (TR)')),
                ('icon', models.CharField(default='school', help_text='Name of a vendored Lucide icon, e.g. graduation-cap.', max_length=40, verbose_name='icon')),
                ('estimated_minutes', models.PositiveIntegerField(default=10, help_text='How long the whole course takes, including doing the work.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='estimated minutes')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20, verbose_name='difficulty')),
                ('required_capability', models.CharField(blank=True, help_text='Only staff holding this capability see the course, e.g. bookings.add. Leave empty to show it to everyone.', max_length=60, verbose_name='required capability')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, verbose_name='sort order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'training course',
                'verbose_name_plural': 'training courses',
                'ordering': ['sort_order', 'code'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('order', models.PositiveIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='order')),
                ('title_en', models.CharField(max_length=200, verbose_name='title (EN)')),
                ('title_tr', models.CharField(max_length=200, verbose_name='title (TR)')),
                ('summary_en', models.TextField(blank=True, verbose_name='summary (EN)')),
                ('summary_tr', models.TextField(blank=True, verbose_name='summary (TR)')),
                ('estimated_minutes', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='estimated minutes')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='training.trainingcourse', verbose_name='course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'training lesson',
                'verbose_name_plural': 'training lessons',
                'ordering': ['course__sort_order', 'order'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('order', models.PositiveIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='order')),
                ('title_en', models.CharField(max_length=200, verbose_name='title (EN)')),
                ('title_tr', models.CharField(max_length=200, verbose_name='title (TR)')),
                ('body_en', models.TextField(blank=True, help_text='Markdown source.', verbose_name='body (EN)')),
                ('body_tr', models.TextField(blank=True, help_text='Markdown source.', verbose_name='body (TR)')),
                ('target_url', models.CharField(blank=True, help_text='The screen this step is about: a URL name such as students:create, or an absolute path such as /students/new/.', max_length=200, verbose_name='target screen')),
                ('action_hint_en', models.CharField(blank=True, max_length=200, verbose_name='action hint (EN)')),
                ('action_hint_tr', models.CharField(blank=True, max_length=200, verbose_name='action hint (TR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='training/steps/%Y/%m/', validators=[apps.core.validators.validate_image_upload], verbose_name='screenshot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='training.traininglesson', verbose_name='lesson')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'training step',
                'verbose_name_plural': 'training steps',
                'ordering': ['lesson__course__sort_order', 'lesson__order', 'order'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=20, verbose_name='status')),
                ('completed_steps', models.JSONField(blank=True, default=list, help_text='Primary keys of the steps this user has ticked off.', verbose_name='completed steps')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last activity')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='training.trainingcourse', verbose_name='course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to='training.traininglesson', verbose_name='current lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to='training.trainingstep', verbose_name='current step')),
            ],
            options={
                'verbose_name': 'training progress',
                'verbose_name_plural': 'training progress',
                'ordering': ['-last_activity_at', 'course__sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['is_active', 'sort_order'], name='train_course_active_order'),
        ),
        migrations.AddIndex(
            model_name='traininglesson',
            index=models.Index(fields=['course', 'order'], name='train_lesson_course_order'),
        ),
        migrations.AddConstraint(
            model_name='traininglesson',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('course', 'order'), name='train_lesson_unique_order'),
        ),
        migrations.AddIndex(
            model_name='trainingstep',
            index=models.Index(fields=['lesson', 'order'], name='train_step_lesson_order'),
        ),
        migrations.AddConstraint(
            model_name='trainingstep',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('lesson', 'order'), name='train_step_unique_order'),
        ),
        migrations.AddIndex(
            model_name='trainingprogress',
            index=models.Index(fields=['user', 'status'], name='train_progress_user_status'),
        ),
        migrations.AddConstraint(
            model_name='trainingprogress',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='train_progress_unique'),
        ),
    ]
