# Generated by Django 5.2.17 on 2026-08-17 22:32

import apps.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.SlugField(help_text='Stable identifier used by imports and integrations, e.g. softboard.', max_length=40, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('icon', models.CharField(default='package', help_text='Name of a vendored Lucide icon, e.g. waves.', max_length=40, verbose_name='icon')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='sort order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='equipment.equipmentcategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'equipment category',
                'verbose_name_plural': 'equipment categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('asset_code', models.CharField(blank=True, help_text='Printed on the QR label. Generated automatically when left blank.', max_length=20, unique=True, verbose_name='asset code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('brand', models.CharField(blank=True, max_length=80, verbose_name='brand')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='model')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='serial number')),
                ('size_label', models.CharField(blank=True, help_text='As printed on the item, e.g. 6\'2" for a board or M for a wetsuit.', max_length=20, verbose_name='size')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[apps.core.validators.validate_not_negative], verbose_name='length (cm)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[apps.core.validators.validate_not_negative], verbose_name='width (cm)')),
                ('thickness_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[apps.core.validators.validate_not_negative], verbose_name='thickness (cm)')),
                ('volume_litres', models.DecimalField(blank=True, decimal_places=2, help_text='Boards only. Drives the board-size recommendation.', max_digits=6, null=True, validators=[apps.core.validators.validate_not_negative], verbose_name='volume (L)')),
                ('wetsuit_thickness', models.CharField(blank=True, help_text='Torso/limb millimetres, e.g. 4/3.', max_length=10, verbose_name='wetsuit thickness')),
                ('suitable_min_level', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], db_index=True, default='first_time', max_length=20, verbose_name='suitable from level')),
                ('suitable_max_level', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], default='competition', max_length=20, verbose_name='suitable up to level')),
                ('min_rider_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[apps.core.validators.validate_not_negative], verbose_name='minimum rider weight (kg)')),
                ('max_rider_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[apps.core.validators.validate_not_negative], verbose_name='maximum rider weight (kg)')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='purchase price')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='current value')),
                ('supplier', models.CharField(blank=True, max_length=120, verbose_name='supplier')),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented out'), ('in_lesson', 'In use — lesson'), ('reserved', 'Reserved'), ('maintenance', 'In maintenance'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('retired', 'Retired')], db_index=True, default='available', max_length=20, verbose_name='status')),
                ('condition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unusable', 'Unusable')], db_index=True, default='good', max_length=20, verbose_name='condition')),
                ('storage_location', models.CharField(blank=True, help_text='Where staff physically find it, e.g. Container A / Rack 3.', max_length=120, verbose_name='storage location')),
                ('is_rentable', models.BooleanField(default=False, help_text='Customers may rent this item. Requires at least one rental price.', verbose_name='rentable')),
                ('is_lesson_stock', models.BooleanField(default=True, help_text='May be handed to students during a lesson.', verbose_name='lesson stock')),
                ('rental_price_hourly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='rental price / hour')),
                ('rental_price_daily', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='rental price / day')),
                ('rental_price_weekly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='rental price / week')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='deposit')),
                ('total_rentals', models.PositiveIntegerField(default=0, verbose_name='total rentals')),
                ('total_rental_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[apps.core.validators.validate_not_negative], verbose_name='total rental hours')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='last service')),
                ('next_maintenance_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='next service due')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='retired at')),
                ('retired_reason', models.CharField(blank=True, max_length=250, verbose_name='retirement reason')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='equipment.equipmentcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'equipment item',
                'verbose_name_plural': 'equipment',
                'ordering': ['asset_code'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to='equipment/photos/%Y/%m/', validators=[apps.core.validators.validate_image_upload], verbose_name='photo')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary photo')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='taken at')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='equipment.equipment', verbose_name='equipment')),
            ],
            options={
                'verbose_name': 'equipment photo',
                'verbose_name_plural': 'equipment photos',
                'ordering': ['-is_primary', '-taken_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentcategory',
            index=models.Index(fields=['parent', 'sort_order'], name='equipment_e_parent__13c381_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status', 'category'], name='equip_status_category_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['is_rentable', 'status'], name='equip_rentable_status_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['next_maintenance_date'], name='equip_next_service_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentphoto',
            index=models.Index(fields=['equipment', '-is_primary'], name='equipment_e_equipme_7d4da1_idx'),
        ),
    ]
