# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('instructors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('student_code', models.CharField(blank=True, db_index=True, help_text='Generated automatically, e.g. STU00001.', max_length=20, unique=True, verbose_name='student code')),
                ('surf_level', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], db_index=True, default='first_time', max_length=20, verbose_name='surf level')),
                ('goals', models.TextField(blank=True, help_text='What does this student want to achieve?', verbose_name='goals')),
                ('stance', models.CharField(choices=[('regular', 'Regular (left foot forward)'), ('goofy', 'Goofy (right foot forward)'), ('unknown', 'Not yet known')], default='unknown', max_length=10, verbose_name='stance')),
                ('board_preference', models.CharField(blank=True, choices=[(None, 'No preference'), ('softtop', 'Soft-top / foamie'), ('longboard', 'Longboard'), ('funboard', 'Funboard / mini-malibu'), ('fish', 'Fish'), ('shortboard', 'Shortboard')], default='', max_length=20, verbose_name='board preference')),
                ('can_swim', models.BooleanField(db_index=True, default=False, help_text='Confirmed by the student or their guardian, not assumed.', verbose_name='can swim')),
                ('swim_distance_m', models.PositiveSmallIntegerField(blank=True, help_text='Unassisted, in open water. 25 m is the usual school minimum.', null=True, verbose_name='swim distance (m)')),
                ('medical_conditions', models.TextField(blank=True, help_text='Asthma, epilepsy, heart conditions, recent surgery, …', verbose_name='medical conditions')),
                ('medications', models.TextField(blank=True, verbose_name='medications')),
                ('allergies', models.TextField(blank=True, verbose_name='allergies')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('10.00')), django.core.validators.MaxValueValidator(Decimal('250.00'))], verbose_name='weight (kg)')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(250)], verbose_name='height (cm)')),
                ('shoe_size', models.PositiveSmallIntegerField(blank=True, help_text='Used for booties.', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(52)], verbose_name='shoe size (EU)')),
                ('wetsuit_size', models.CharField(blank=True, help_text="As labelled on the school's suits, e.g. MS, L, JR12.", max_length=10, verbose_name='wetsuit size')),
                ('total_lessons', models.PositiveIntegerField(default=0, verbose_name='lessons taken')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='hours in the water')),
                ('last_lesson_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='last lesson')),
                ('joined_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='joined on')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to='customers.customer', verbose_name='customer')),
                ('preferred_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferring_students', to='instructors.instructor', verbose_name='preferred instructor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['customer__last_name', 'customer__first_name'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('assessed_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='assessed on')),
                ('level_before', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], max_length=20, verbose_name='level before')),
                ('level_after', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], max_length=20, verbose_name='level after')),
                ('paddling', models.PositiveSmallIntegerField(help_text='1 = struggling, 5 = strong', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='paddling')),
                ('popup', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='pop-up')),
                ('positioning', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='positioning')),
                ('wave_reading', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='wave reading')),
                ('safety', models.PositiveSmallIntegerField(help_text='Rips, other surfers, board control, self-rescue.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='safety awareness')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('next_focus', models.CharField(blank=True, help_text='The one thing to work on in the next session.', max_length=200, verbose_name='next focus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_assessments', to='instructors.instructor', verbose_name='instructor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'skill assessment',
                'verbose_name_plural': 'skill assessments',
                'ordering': ['-assessed_on', '-created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['surf_level', 'is_active'], name='students_st_surf_le_cf33ef_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['-last_lesson_date'], name='students_st_last_le_cfd3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['preferred_instructor', 'is_active'], name='students_st_preferr_05329c_idx'),
        ),
        migrations.AddIndex(
            model_name='skillassessment',
            index=models.Index(fields=['student', '-assessed_on'], name='students_sk_student_c40fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='skillassessment',
            index=models.Index(fields=['instructor', '-assessed_on'], name='students_sk_instruc_73e3c1_idx'),
        ),
    ]
