# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('value', models.TextField(blank=True, verbose_name='value')),
                ('value_type', models.CharField(choices=[('string', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Yes / No'), ('json', 'JSON')], default='string', max_length=10, verbose_name='type')),
                ('group', models.CharField(db_index=True, default='general', max_length=50, verbose_name='group')),
                ('label_en', models.CharField(blank=True, max_length=150, verbose_name='label (EN)')),
                ('label_tr', models.CharField(blank=True, max_length=150, verbose_name='label (TR)')),
                ('is_secret', models.BooleanField(default=False, help_text='Secret values are masked in the UI and never logged.', verbose_name='secret')),
            ],
            options={
                'verbose_name': 'system setting',
                'verbose_name_plural': 'system settings',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('color', models.CharField(default='#0ea5e9', help_text='Hex colour used for the badge, e.g. #0ea5e9', max_length=7, verbose_name='color')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('category', models.CharField(choices=[('waiver', 'Waiver / consent form'), ('certificate', 'Certificate'), ('identity', 'Identity document'), ('medical', 'Medical information'), ('insurance', 'Insurance'), ('invoice', 'Invoice'), ('contract', 'Contract'), ('photo', 'Photo'), ('manual', 'Manual / procedure'), ('other', 'Other')], default='other', max_length=20, verbose_name='category')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='file')),
                ('content_type_hint', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='size (bytes)')),
                ('expires_on', models.DateField(blank=True, help_text='Used for certificates and insurance.', null=True, verbose_name='expires on')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='confidential')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_docume_content_343c2e_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('object_id', models.PositiveIntegerField()),
                ('body', models.TextField(verbose_name='note')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes are never shown to customers.', verbose_name='internal only')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_note_content_948980_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
