# Generated by Django 5.2.17 on 2026-08-17 22:32

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('code', models.CharField(blank=True, help_text='Short reference used on manifests and radio calls.', max_length=12, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('latitude', models.FloatField(validators=[apps.core.validators.validate_latitude], verbose_name='latitude')),
                ('longitude', models.FloatField(validators=[apps.core.validators.validate_longitude], verbose_name='longitude')),
                ('altitude', models.FloatField(blank=True, help_text='Height of the access point above sea level, in metres.', null=True, verbose_name='altitude (m)')),
                ('beach_facing_deg', models.FloatField(help_text='Compass direction you look towards when standing on the sand facing the water. Required — wind is classified relative to this bearing.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(360.0)], verbose_name='beach facing (°)')),
                ('break_type', models.CharField(choices=[('beach_break', 'Beach break'), ('point_break', 'Point break'), ('reef_break', 'Reef break'), ('river_mouth', 'River mouth')], db_index=True, default='beach_break', max_length=20, verbose_name='break type')),
                ('bottom_type', models.CharField(choices=[('sand', 'Sand'), ('reef', 'Reef'), ('rock', 'Rock'), ('mixed', 'Mixed')], db_index=True, default='sand', max_length=10, verbose_name='bottom type')),
                ('min_level', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], db_index=True, default='first_time', help_text='The least experienced surfer this break is safe for.', max_length=20, verbose_name='minimum level')),
                ('max_level', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], db_index=True, default='competition', help_text='The most advanced level this break still suits.', max_length=20, verbose_name='maximum level')),
                ('ideal_tide', models.CharField(choices=[('low', 'Low tide'), ('mid_rising', 'Mid — rising'), ('high', 'High tide'), ('mid_falling', 'Mid — falling'), ('unknown', 'Unknown')], default='mid_rising', max_length=15, verbose_name='ideal tide')),
                ('ideal_wind', models.CharField(choices=[('offshore', 'Offshore'), ('cross_offshore', 'Cross-offshore'), ('cross_shore', 'Cross-shore'), ('cross_onshore', 'Cross-onshore'), ('onshore', 'Onshore'), ('glassy', 'Glassy / no wind')], default='offshore', max_length=20, verbose_name='ideal wind')),
                ('ideal_swell_direction_deg', models.FloatField(blank=True, help_text='Bearing the best swell arrives from.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(360.0)], verbose_name='ideal swell direction (°)')),
                ('capacity', models.PositiveIntegerField(default=20, help_text='Maximum number of students the school puts in the water here at once.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacity')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_primary', models.BooleanField(default=False, help_text='The spot used when nothing else is chosen. Only one spot may hold this.', verbose_name='default spot')),
                ('parking_info', models.TextField(blank=True, verbose_name='parking')),
                ('access_notes', models.TextField(blank=True, help_text='How to reach the water: path, steps, vehicle access, walking time.', verbose_name='access notes')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='locations/spots/%Y/%m/', validators=[apps.core.validators.validate_image_upload], verbose_name='photo')),
                ('lifeguard_on_duty', models.BooleanField(db_index=True, default=False, help_text='A patrolled beach with a lifeguard service during the season.', verbose_name='lifeguard service')),
                ('nearest_hospital', models.CharField(blank=True, max_length=200, verbose_name='nearest hospital')),
                ('nearest_hospital_phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +90 555 123 45 67.', regex='^\\+?[0-9 ()\\-]{6,25}$')], verbose_name='hospital phone')),
                ('emergency_notes', models.TextField(blank=True, help_text='Ambulance meeting point, mobile coverage, nearest defibrillator.', verbose_name='emergency notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'surf spot',
                'verbose_name_plural': 'surf spots',
                'ordering': ['-is_primary', 'name'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpotHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='hazard')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10, verbose_name='severity')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('applies_from_tide', models.CharField(blank=True, choices=[('low', 'Low tide'), ('mid_rising', 'Mid — rising'), ('high', 'High tide'), ('mid_falling', 'Mid — falling'), ('unknown', 'Unknown')], help_text='Leave both tide fields empty if the hazard is present at every tide.', max_length=15, verbose_name='applies from tide')),
                ('applies_to_tide', models.CharField(blank=True, choices=[('low', 'Low tide'), ('mid_rising', 'Mid — rising'), ('high', 'High tide'), ('mid_falling', 'Mid — falling'), ('unknown', 'Unknown')], max_length=15, verbose_name='applies to tide')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='locations.surfspot', verbose_name='surf spot')),
            ],
            options={
                'verbose_name': 'spot hazard',
                'verbose_name_plural': 'spot hazards',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='surfspot',
            index=models.Index(fields=['is_active', 'is_primary'], name='loc_spot_active_primary'),
        ),
        migrations.AddIndex(
            model_name='surfspot',
            index=models.Index(fields=['min_level', 'max_level'], name='loc_spot_level_range'),
        ),
        migrations.AddConstraint(
            model_name='surfspot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_primary', True)), fields=('is_primary',), name='loc_spot_single_primary'),
        ),
        migrations.AddIndex(
            model_name='spothazard',
            index=models.Index(fields=['spot', 'is_active'], name='loc_hazard_spot_active'),
        ),
    ]
