# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.SlugField(help_text='Stable identifier used in URLs, e.g. getting-started.', unique=True, validators=[django.core.validators.RegexValidator(message='Use 2–50 letters, digits, hyphens or underscores.', regex='^[A-Za-z0-9][A-Za-z0-9_\\-]{1,49}$')], verbose_name='code')),
                ('name_en', models.CharField(max_length=150, verbose_name='name (EN)')),
                ('name_tr', models.CharField(max_length=150, verbose_name='name (TR)')),
                ('icon', models.CharField(default='circle-help', help_text='Name of a vendored Lucide icon, e.g. graduation-cap.', max_length=40, verbose_name='icon')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, verbose_name='sort order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'help category',
                'verbose_name_plural': 'help categories',
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='help_cat_active_order')],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('slug', models.SlugField(blank=True, help_text='Permanent address of the article. Generated from the English title.', max_length=160, unique=True, verbose_name='slug')),
                ('title_en', models.CharField(max_length=200, verbose_name='title (EN)')),
                ('title_tr', models.CharField(max_length=200, verbose_name='title (TR)')),
                ('body_en', models.TextField(help_text='Markdown source.', verbose_name='body (EN)')),
                ('body_tr', models.TextField(help_text='Markdown source.', verbose_name='body (TR)')),
                ('keywords', models.CharField(blank=True, db_index=True, help_text='Comma-separated search terms in both languages.', max_length=300, verbose_name='keywords')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, verbose_name='sort order')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='views')),
                ('helpful_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='marked helpful')),
                ('not_helpful_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='marked not helpful')),
                ('related_module', models.CharField(blank=True, choices=[('dashboard', 'Dashboard'), ('accounts', 'Users & Roles'), ('customers', 'Customers'), ('students', 'Students'), ('instructors', 'Instructors'), ('crm', 'CRM'), ('locations', 'Surf Locations'), ('lessons', 'Lessons'), ('bookings', 'Bookings'), ('surf_camps', 'Surf Camps'), ('equipment', 'Equipment'), ('rentals', 'Rentals'), ('maintenance', 'Maintenance'), ('surf_conditions', 'Surf Conditions'), ('safety', 'Safety'), ('finance', 'Finance'), ('pos', 'Point of Sale'), ('analytics', 'Analytics'), ('reporting', 'Reports'), ('notifications', 'Notifications'), ('backups', 'Backup & Restore'), ('audit', 'Audit Log'), ('ai', 'AI Assistant'), ('ai_terminal', 'AI Development Terminal'), ('help_center', 'Help Center'), ('training', 'Training Center'), ('onboarding', 'Onboarding'), ('settings', 'Settings')], db_index=True, help_text='The part of the system this article documents.', max_length=50, verbose_name='related module')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='help_center.helpcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'help article',
                'verbose_name_plural': 'help articles',
                'ordering': ['category__sort_order', 'sort_order', 'title_en'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['category', 'sort_order'], name='help_art_cat_order'), models.Index(fields=['is_published', 'sort_order'], name='help_art_pub_order'), models.Index(fields=['related_module', 'is_published'], name='help_art_module_pub')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
