# Generated by Django 5.2.17 on 2026-08-17 22:32

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('interval_days', models.PositiveIntegerField(default=90, help_text='How often the check list below must be worked through.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='interval (days)')),
                ('last_performed_on', models.DateField(blank=True, null=True, verbose_name='last performed on')),
                ('next_due_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='next due on')),
                ('check_items', models.JSONField(blank=True, default=list, help_text='The individual checks to perform, one per line.', verbose_name='check list')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'maintenance schedule',
                'verbose_name_plural': 'maintenance schedules',
                'ordering': ['next_due_on', 'id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('record_code', models.CharField(db_index=True, help_text='Automatically assigned, e.g. MNT00001.', max_length=20, unique=True, verbose_name='record code')),
                ('damage_type', models.CharField(choices=[('ding', 'Ding'), ('crack', 'Crack'), ('fin_damage', 'Fin damage'), ('leash_damage', 'Leash damage'), ('wetsuit_tear', 'Wetsuit tear'), ('zipper', 'Zipper failure'), ('water_damage', 'Water damage / delamination'), ('delamination', 'Delamination'), ('snapped', 'Snapped board'), ('general', 'General maintenance'), ('other', 'Other')], db_index=True, default='general', max_length=20, verbose_name='damage type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10, verbose_name='severity')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20, verbose_name='status')),
                ('reported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='reported at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='work started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('description', models.TextField(help_text='What was found, where on the item, and how it happened.', verbose_name='problem description')),
                ('diagnosis', models.TextField(blank=True, verbose_name='diagnosis')),
                ('resolution', models.TextField(blank=True, verbose_name='resolution')),
                ('parts_used', models.TextField(blank=True, help_text="One per line, e.g. 'epoxy resin 250 ml'.", verbose_name='parts and materials used')),
                ('labour_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='labour hours')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='parts cost')),
                ('labour_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='labour cost')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total cost')),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='maintenance/%Y/%m/', validators=[apps.core.validators.validate_image_upload], verbose_name='photo — before')),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='maintenance/%Y/%m/', validators=[apps.core.validators.validate_image_upload], verbose_name='photo — after')),
                ('made_unusable', models.BooleanField(default=True, help_text='Whether the item was withdrawn from rentals and lessons.', verbose_name='taken out of service')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='equipment.equipment', verbose_name='equipment')),
            ],
            options={
                'verbose_name': 'maintenance record',
                'verbose_name_plural': 'maintenance records',
                'ordering': ['-reported_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
