# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='rental_item',
            field=models.ForeignKey(blank=True, help_text='Set when the damage was discovered as a rental came back.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='rentals.rentalitem', verbose_name='found on rental return'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='reported by'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedule', to='equipment.equipment', verbose_name='equipment'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['status', 'severity'], name='maintenance_status_98922b_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['equipment', '-reported_at'], name='maintenance_equipme_b9c135_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['-reported_at'], name='maintenance_reporte_9af54f_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['is_active', 'next_due_on'], name='maintenance_is_acti_82b534_idx'),
        ),
    ]
