"""Markdown rendering, sanitising and language selection for guidance content.

Why this module exists
----------------------
Help articles and training steps are Markdown stored in the database and edited
through the Django admin. Admin-editable therefore means *untrusted*: a
compromised or careless staff account must not be able to plant a script tag on
a page every colleague opens. So the pipeline is always

    Markdown source -> HTML (python-markdown) -> bleach.clean(strip=True)

and only the sanitised result is ever marked safe.

The same module resolves the ``*_en`` / ``*_tr`` field pairs against the active
language, with a deterministic fallback chain so a half-translated article still
renders something useful instead of an empty page.

``apps.training`` imports from here on purpose: both modules render exactly the
same flavour of operator-authored Markdown, and one sanitiser configuration is
easier to audit than two.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

import bleach
import markdown
from django.conf import settings
from django.utils.safestring import SafeString, mark_safe
from django.utils.translation import get_language

# ---------------------------------------------------------------------------
# Sanitiser policy
# ---------------------------------------------------------------------------
#: Structural and inline tags a procedure document legitimately needs. Anything
#: else (script, style, iframe, form, object, embed, …) is stripped outright.
ALLOWED_TAGS: frozenset[str] = frozenset(
    {
        "p", "br", "hr",
        "h1", "h2", "h3", "h4", "h5", "h6",
        "ul", "ol", "li",
        "dl", "dt", "dd",
        "strong", "b", "em", "i", "u", "s", "del", "ins", "mark",
        "sup", "sub", "small", "abbr", "kbd", "samp", "var",
        "code", "pre", "blockquote", "span", "div",
        "a", "img",
        "table", "thead", "tbody", "tfoot", "tr", "th", "td", "caption",
    }
)

#: Attribute allow-list. ``id`` is permitted everywhere because the table of
#: contents links to heading anchors generated by the ``toc`` extension.
ALLOWED_ATTRIBUTES: dict[str, list[str]] = {
    "*": ["id"],
    "a": ["href", "title", "rel", "target"],
    "img": ["src", "alt", "title", "width", "height", "loading"],
    "code": ["class"],
    "pre": ["class"],
    "span": ["class"],
    "div": ["class"],
    "abbr": ["title"],
    "th": ["align", "colspan", "rowspan", "scope"],
    "td": ["align", "colspan", "rowspan"],
    "ol": ["start", "type"],
}

#: ``javascript:`` and ``data:`` URLs are deliberately absent.
ALLOWED_PROTOCOLS: frozenset[str] = frozenset({"http", "https", "mailto", "tel"})

#: Markdown extensions. ``attr_list`` and ``md_in_html`` are deliberately not
#: enabled — they widen the attack surface for no editorial benefit here.
#: Elements whose *content* is executable or styling rather than prose. bleach
#: strips the tag but keeps the text, so these are removed whole beforehand.
_DANGEROUS_TAGS = ("script", "style", "iframe", "object", "embed", "noscript", "template")
_DANGEROUS_NAMES = "|".join(_DANGEROUS_TAGS)

#: A complete dangerous element, its content included.
_DANGEROUS_BLOCK_RE = re.compile(
    rf"<\s*({_DANGEROUS_NAMES})\b[^>]*>.*?<\s*/\s*\1\s*>",
    re.IGNORECASE | re.DOTALL,
)

#: An unclosed dangerous tag is no safer than a closed one, so everything
#: from the opening tag onwards is dropped as well.
_DANGEROUS_OPEN_RE = re.compile(
    rf"<\s*({_DANGEROUS_NAMES})\b[^>]*>.*",
    re.IGNORECASE | re.DOTALL,
)

MARKDOWN_EXTENSIONS: tuple[str, ...] = ("fenced_code", "tables", "sane_lists", "toc")

MARKDOWN_EXTENSION_CONFIGS: dict[str, dict] = {
    # baselevel 1 (the default): the page already renders the article title as
    # its <h1>, and authors write "##" for sections — so "##" must become <h2>.
    # Offsetting to baselevel 2 turned every section into <h3> and left the
    # document with no <h2> at all, which is a heading-order defect for screen
    # readers as well as a surprise for authors.
    "toc": {"permalink": False, "baselevel": 1, "toc_depth": "2-4"},
}

_WORD_RE = re.compile(r"\w+", re.UNICODE)
_TAG_RE = re.compile(r"<[^>]+>")

#: Average reading speed used for the "x min read" hint.
WORDS_PER_MINUTE = 200


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class RenderedContent:
    """The result of rendering one Markdown document."""

    html: SafeString
    headings: list[dict] = field(default_factory=list)
    reading_minutes: int = 1

    @property
    def has_toc(self) -> bool:
        return len(self.headings) > 1


def _flatten_toc(tokens: list[dict], collected: list[dict]) -> list[dict]:
    """Flatten python-markdown's nested ``toc_tokens`` into an ordered list."""
    for token in tokens:
        collected.append(
            {
                "id": token.get("id", ""),
                "name": _TAG_RE.sub("", token.get("name", "")).strip(),
                "level": int(token.get("level", 2)),
            }
        )
        children = token.get("children") or []
        if children:
            _flatten_toc(children, collected)
    return collected


def reading_minutes(source: str) -> int:
    """Estimated reading time in whole minutes (never less than one)."""
    words = len(_WORD_RE.findall(source or ""))
    return max(1, round(words / WORDS_PER_MINUTE)) if words else 1


def render_content(source: str) -> RenderedContent:
    """Render *source* Markdown to sanitised HTML plus its heading outline."""
    text = source or ""
    if not text.strip():
        return RenderedContent(html=mark_safe(""), headings=[], reading_minutes=1)  # nosec B308

    converter = markdown.Markdown(
        extensions=list(MARKDOWN_EXTENSIONS),
        extension_configs=MARKDOWN_EXTENSION_CONFIGS,
        output_format="html",
    )
    raw_html = converter.convert(text)
    headings = _flatten_toc(getattr(converter, "toc_tokens", []) or [], [])

    # bleach with strip=True removes a tag but KEEPS its text, so
    # "<script>alert(1)</script>" would leave "alert(1)" visible in the article.
    # For elements whose content is code rather than prose, the content has to
    # go with the tag. Done before bleach so nothing depends on ordering.
    raw_html = _DANGEROUS_BLOCK_RE.sub("", raw_html)
    raw_html = _DANGEROUS_OPEN_RE.sub("", raw_html)

    clean_html = bleach.clean(
        raw_html,
        tags=set(ALLOWED_TAGS),
        attributes=ALLOWED_ATTRIBUTES,
        protocols=set(ALLOWED_PROTOCOLS),
        strip=True,
        strip_comments=True,
    )

    # Safe: the string above is the output of bleach with an explicit allow-list,
    # so no author-supplied markup survives that a browser would execute.
    return RenderedContent(
        html=mark_safe(clean_html),  # noqa: S308 - sanitised on the line above  # nosec
        headings=[h for h in headings if h["id"] and h["name"]],
        reading_minutes=reading_minutes(text),
    )


def plain_text(source: str, limit: int = 240) -> str:
    """A short, tag-free excerpt of a Markdown document, for cards and search."""
    text = _TAG_RE.sub(" ", source or "")
    text = re.sub(r"[#>*_`\[\]()!-]{1,}", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) <= limit:
        return text
    return text[: limit - 1].rsplit(" ", 1)[0] + "…"


# ---------------------------------------------------------------------------
# Language-aware field pairs
# ---------------------------------------------------------------------------
#: Order in which translations are tried when the active language has none.
FALLBACK_LANGUAGES: tuple[str, ...] = ("en", "tr")


def active_language() -> str:
    """The two-letter code of the language the current request is rendering in."""
    code = get_language() or getattr(settings, "LANGUAGE_CODE", "en") or "en"
    return str(code).split("-")[0].lower()


def localized(instance, base: str, default: str = "") -> str:
    """Return ``<base>_<language>`` for *instance*, falling back sensibly.

    ``localized(article, "title")`` reads ``title_tr`` under Turkish and
    ``title_en`` under English. A missing or empty translation falls back to
    English, then Turkish, then *default* — an operator never sees a blank
    heading because one language was left unfilled.
    """
    language = active_language()
    value = (getattr(instance, f"{base}_{language}", "") or "").strip()
    if value:
        return value
    for fallback in FALLBACK_LANGUAGES:
        value = (getattr(instance, f"{base}_{fallback}", "") or "").strip()
        if value:
            return value
    return default
