# Generated by Django 5.2.17 on 2026-08-18 05:19

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='completed')),
                ('is_dismissed', models.BooleanField(default=False, help_text='The operator chose to skip setup; hide the dashboard banner.', verbose_name='dismissed')),
                ('current_step', models.PositiveIntegerField(default=1, help_text='1-based index into STEPS of the step last shown.', verbose_name='current step')),
                ('completed_steps', models.JSONField(blank=True, default=list, help_text='Keys of the steps that were answered rather than skipped.', verbose_name='completed steps')),
                ('school_name', models.CharField(blank=True, max_length=150, verbose_name='school name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact e-mail')),
                ('contact_phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +90 555 123 45 67.', regex='^\\+?[0-9 ()\\-]{6,25}$')], verbose_name='contact phone')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='address')),
                ('default_language', models.CharField(default='tr', max_length=5, verbose_name='default language')),
                ('currency', models.CharField(choices=[('TRY', 'Turkish lira (₺)'), ('EUR', 'Euro (€)'), ('USD', 'US dollar ($)'), ('GBP', 'Pound sterling (£)')], default='TRY', max_length=3, verbose_name='currency')),
                ('timezone', models.CharField(default='Europe/Istanbul', help_text='IANA name, e.g. Europe/Istanbul.', max_length=64, verbose_name='time zone')),
                ('primary_spot_name', models.CharField(blank=True, max_length=120, verbose_name='primary surf spot')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[apps.core.validators.validate_latitude], verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[apps.core.validators.validate_longitude], verbose_name='longitude')),
                ('beach_facing_deg', models.FloatField(blank=True, help_text='Compass direction you look towards when standing on the sand facing the water. Wind quality is classified against it.', null=True, verbose_name='beach facing (°)')),
                ('staff_invited', models.BooleanField(default=False, verbose_name='staff added')),
                ('ai_configured', models.BooleanField(default=False, verbose_name='AI configured')),
                ('backup_configured', models.BooleanField(default=False, verbose_name='backup configured')),
                ('records_created', models.BooleanField(default=False, verbose_name='records created')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_sessions', to=settings.AUTH_USER_MODEL, verbose_name='started by')),
            ],
            options={
                'verbose_name': 'onboarding state',
                'verbose_name_plural': 'onboarding state',
                'ordering': ['pk'],
            },
        ),
    ]
