# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('first_name', models.CharField(max_length=80, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='last name')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +90 555 123 45 67.', regex='^\\+?[0-9 ()\\-]{6,25}$')], verbose_name='phone')),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('phone', 'Phone'), ('email', 'E-mail'), ('website', 'Website'), ('partner', 'Partner / agency'), ('social', 'Social media'), ('returning', 'Returning customer'), ('other', 'Other')], db_index=True, default='website', max_length=20, verbose_name='source')),
                ('interest', models.TextField(blank=True, help_text='What the person asked for: level, dates, group size, budget.', verbose_name='interest')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal sent'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('expected_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated revenue if this lead converts.', max_digits=12, verbose_name='expected value')),
                ('probability', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Chance of winning this lead, from 0 to 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='probability (%)')),
                ('next_action', models.CharField(blank=True, help_text='The single next step, e.g. “Call back about August dates”.', max_length=200, verbose_name='next action')),
                ('next_action_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='next action due')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='converted at')),
                ('lost_reason', models.CharField(blank=True, max_length=200, verbose_name='lost reason')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_leads', to='customers.customer', verbose_name='converted customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('kind', models.CharField(choices=[('call', 'Phone call'), ('email', 'E-mail'), ('meeting', 'Meeting'), ('message', 'Message / chat'), ('visit', 'Visit'), ('review', 'Review'), ('complaint', 'Complaint'), ('note', 'Internal note')], db_index=True, default='call', max_length=20, verbose_name='type')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, default='outbound', max_length=10, verbose_name='direction')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('body', models.TextField(blank=True, verbose_name='details')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='occurred at')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1440)], verbose_name='duration (minutes)')),
                ('follow_up_required', models.BooleanField(db_index=True, default=False, verbose_name='follow-up required')),
                ('follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='follow-up due')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10, verbose_name='sentiment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='customers.customer', verbose_name='customer')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_interactions', to=settings.AUTH_USER_MODEL, verbose_name='handled by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'interaction',
                'verbose_name_plural': 'interactions',
                'ordering': ['-occurred_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('criteria', models.JSONField(blank=True, default=dict, help_text='Declarative audience filter, e.g. surf level, consent, visit recency.', verbose_name='criteria')),
                ('is_dynamic', models.BooleanField(default=True, help_text='Dynamic segments are re-evaluated every time they are used.', verbose_name='dynamic')),
                ('cached_count', models.PositiveIntegerField(default=0, verbose_name='cached size')),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='last calculated')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'segment',
                'verbose_name_plural': 'segments',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('code', models.CharField(blank=True, help_text='Left blank, a code such as CMP00007 is generated.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Use 2–50 letters, digits, hyphens or underscores.', regex='^[A-Za-z0-9][A-Za-z0-9_\\-]{1,49}$')], verbose_name='code')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('social', 'Social media'), ('print', 'Print'), ('partner', 'Partner / agency'), ('event', 'Event')], db_index=True, default='email', max_length=20, verbose_name='channel')),
                ('start_date', models.DateField(db_index=True, verbose_name='start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='end date')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='budget')),
                ('actual_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='actual spend')),
                ('message_subject', models.CharField(blank=True, max_length=200, verbose_name='message subject')),
                ('message_body', models.TextField(blank=True, verbose_name='message body')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='sent')),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name='opened')),
                ('converted_count', models.PositiveIntegerField(default=0, verbose_name='converted')),
                ('revenue_attributed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='revenue attributed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('target_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='crm.segment', verbose_name='target segment')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'ordering': ['-start_date', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', '-created_at'], name='crm_lead_status_created'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'next_action_at'], name='crm_lead_owner_due'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'status'], name='crm_lead_source_status'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('probability__gte', 0), ('probability__lte', 100)), name='crm_lead_probability_range'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('expected_value__gte', 0)), name='crm_lead_expected_value_not_negative'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['customer', '-occurred_at'], name='crm_inter_customer_time'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['lead', '-occurred_at'], name='crm_inter_lead_time'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['follow_up_required', 'follow_up_at'], name='crm_inter_followup'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['kind', '-occurred_at'], name='crm_inter_kind_time'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['is_dynamic', 'name'], name='crm_segment_dynamic_name'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', '-start_date'], name='crm_campaign_status_start'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['channel', 'status'], name='crm_campaign_channel_status'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='crm_campaign_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('budget__gte', 0), ('actual_spend__gte', 0)), name='crm_campaign_money_not_negative'),
        ),
    ]
