# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('provider', models.CharField(max_length=32, unique=True, verbose_name='provider')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('base_url_override', models.CharField(blank=True, max_length=300, verbose_name='base URL override')),
                ('model_overrides', models.JSONField(blank=True, default=dict, help_text='Role → model id, e.g. {"assistant": "nvidia/nemotron-3-super-120b-a12b"}', verbose_name='model overrides')),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 means no limit. Requests are blocked once the budget is reached.', max_digits=12, verbose_name='monthly budget (USD)')),
                ('last_health_ok', models.BooleanField(default=False, verbose_name='last health check passed')),
                ('last_health_message', models.CharField(blank=True, max_length=500, verbose_name='last health message')),
                ('last_health_at', models.DateTimeField(blank=True, null=True, verbose_name='last checked')),
                ('last_latency_ms', models.PositiveIntegerField(default=0, verbose_name='last latency (ms)')),
                ('probed_models', models.JSONField(blank=True, default=dict, verbose_name='probed models')),
            ],
            options={
                'verbose_name': 'AI provider configuration',
                'verbose_name_plural': 'AI provider configurations',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('kind', models.CharField(choices=[('assistant', 'Business assistant'), ('terminal', 'Development terminal'), ('analysis', 'Analysis')], default='assistant', max_length=16, verbose_name='kind')),
                ('routing_mode', models.CharField(default='local_only', max_length=16, verbose_name='routing mode')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='total tokens')),
                ('total_cost', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12, verbose_name='total cost (USD)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI conversation',
                'verbose_name_plural': 'AI conversations',
                'ordering': ['-is_pinned', '-updated_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool result')], max_length=16, verbose_name='role')),
                ('content', models.TextField(verbose_name='content')),
                ('reasoning', models.TextField(blank=True, verbose_name='reasoning')),
                ('tool_calls', models.JSONField(blank=True, default=list, verbose_name='tool calls')),
                ('tool_name', models.CharField(blank=True, max_length=100, verbose_name='tool name')),
                ('provider', models.CharField(blank=True, max_length=32, verbose_name='provider')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='model')),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('used_fallback', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=500, verbose_name='error')),
                ('citations', models.JSONField(blank=True, default=list, verbose_name='citations')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation')),
            ],
            options={
                'verbose_name': 'AI message',
                'verbose_name_plural': 'AI messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('provider', models.CharField(db_index=True, max_length=32, verbose_name='provider')),
                ('model', models.CharField(db_index=True, max_length=120, verbose_name='model')),
                ('role', models.CharField(blank=True, max_length=32, verbose_name='role')),
                ('operation', models.CharField(choices=[('chat', 'Chat'), ('tool_call', 'Tool call'), ('embedding', 'Embedding'), ('analysis', 'Analysis'), ('terminal', 'Development terminal'), ('translation', 'Translation'), ('vision', 'Vision'), ('health_check', 'Health check')], default='chat', max_length=16, verbose_name='operation')),
                ('is_cloud', models.BooleanField(db_index=True, default=False, verbose_name='cloud')),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(db_index=True, default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12, verbose_name='estimated cost (USD)')),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('was_successful', models.BooleanField(default=True)),
                ('used_fallback', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage', to='ai.aiconversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI usage record',
                'verbose_name_plural': 'AI usage records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RagDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('policy', 'Policy'), ('training', 'Training material'), ('safety', 'Safety procedure'), ('equipment', 'Equipment manual'), ('internal', 'Internal document'), ('help', 'Help article'), ('database', 'Database record')], default='internal', max_length=20, verbose_name='type')),
                ('language', models.CharField(default='tr', max_length=5, verbose_name='language')),
                ('content', models.TextField(verbose_name='content')),
                ('file', models.FileField(blank=True, null=True, upload_to='rag/%Y/%m/', verbose_name='file')),
                ('source_url', models.CharField(blank=True, max_length=500, verbose_name='source')),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='checksum')),
                ('is_indexed', models.BooleanField(db_index=True, default=False, verbose_name='indexed')),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='indexed at')),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='chunks')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'knowledge document',
                'verbose_name_plural': 'knowledge base',
                'ordering': ['-updated_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RagChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('chunk_index', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('content', models.TextField(verbose_name='content')),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(default=list, verbose_name='embedding')),
                ('embedding_model', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='embedding model')),
                ('embedding_dimensions', models.PositiveIntegerField(db_index=True, default=0, verbose_name='dimensions')),
                ('embedding_norm', models.FloatField(default=0.0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.ragdocument')),
            ],
            options={
                'verbose_name': 'knowledge chunk',
                'verbose_name_plural': 'knowledge chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', '-updated_at'], name='ai_aiconver_user_id_fe4cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagerecord',
            index=models.Index(fields=['-created_at'], name='ai_aiusager_created_792e54_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagerecord',
            index=models.Index(fields=['provider', '-created_at'], name='ai_aiusager_provide_01072e_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagerecord',
            index=models.Index(fields=['user', '-created_at'], name='ai_aiusager_user_id_ef0528_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchunk',
            index=models.Index(fields=['embedding_model', 'embedding_dimensions'], name='ai_ragchunk_embeddi_564177_idx'),
        ),
        migrations.AddConstraint(
            model_name='ragchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_chunk_position'),
        ),
    ]
