# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='username')),
                ('user_role', models.CharField(blank=True, max_length=32, verbose_name='role')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('login', 'Signed in'), ('logout', 'Signed out'), ('login_failed', 'Sign-in failed'), ('password_change', 'Password changed'), ('permission_change', 'Permissions changed'), ('payment', 'Payment recorded'), ('refund', 'Refund issued'), ('booking_change', 'Booking changed'), ('booking_cancel', 'Booking cancelled'), ('rental_out', 'Equipment checked out'), ('rental_return', 'Equipment returned'), ('backup_create', 'Backup created'), ('backup_restore', 'Backup restored'), ('backup_delete', 'Backup deleted'), ('export', 'Data exported'), ('ai_query', 'AI query'), ('ai_action', 'AI-performed change'), ('ai_command_proposed', 'AI command proposed'), ('ai_command_approved', 'AI command approved'), ('ai_command_rejected', 'AI command rejected'), ('ai_command_executed', 'AI command executed'), ('safety_incident', 'Safety incident recorded'), ('settings_change', 'Settings changed'), ('system', 'System event')], db_index=True, max_length=32, verbose_name='action')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Mapping of field -> [old, new]. Secrets are redacted before storage.', verbose_name='changes')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='object id')),
                ('object_repr', models.CharField(blank=True, max_length=250, verbose_name='object')),
                ('source', models.CharField(choices=[('web', 'Web interface'), ('api', 'REST API'), ('admin', 'Django admin'), ('ai', 'AI assistant'), ('ai_terminal', 'AI development terminal'), ('system', 'Background task'), ('cli', 'Command line')], default='web', max_length=16, verbose_name='source')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='user agent')),
                ('request_path', models.CharField(blank=True, max_length=400, verbose_name='path')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36, verbose_name='request id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Marks entries that must be retained for compliance.', verbose_name='sensitive')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx')],
            },
        ),
    ]
