# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='requested at')),
                ('participants', models.PositiveSmallIntegerField(default=1, verbose_name='seats wanted')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='position')),
                ('is_notified', models.BooleanField(default=False, verbose_name='notified')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='notified at')),
                ('is_converted', models.BooleanField(db_index=True, default=False, verbose_name='converted')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='note')),
            ],
            options={
                'verbose_name': 'waiting-list entry',
                'verbose_name_plural': 'waiting list',
                'ordering': ['requested_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('booking_code', models.CharField(db_index=True, help_text='Reference given to the customer, e.g. BK000001.', max_length=20, unique=True, verbose_name='booking code')),
                ('booking_type', models.CharField(choices=[('lesson', 'Lesson'), ('camp', 'Surf camp'), ('rental', 'Equipment rental'), ('package', 'Lesson package')], db_index=True, default='lesson', max_length=10, verbose_name='type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], db_index=True, default='pending', max_length=12, verbose_name='status')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('overdue', 'Overdue')], db_index=True, default='unpaid', max_length=10, verbose_name='payment status')),
                ('participants', models.PositiveSmallIntegerField(default=1, help_text='Number of seats this booking occupies.', verbose_name='participants')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='price per participant')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='discount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='paid')),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('phone', 'Phone'), ('email', 'E-mail'), ('website', 'Website'), ('partner', 'Partner / agency'), ('social', 'Social media'), ('returning', 'Returning customer'), ('other', 'Other')], db_index=True, default='walk_in', max_length=12, verbose_name='source')),
                ('booked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='booked at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='cancellation fee')),
                ('special_requests', models.TextField(blank=True, help_text='Visible to the instructor: allergies, fears, kit sizes, languages.', verbose_name='special requests')),
                ('internal_notes', models.TextField(blank=True, help_text='Never shown to the customer.', verbose_name='internal notes')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='reminder sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='reminder sent at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(help_text='The person who pays for and owns this booking.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-booked_at', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
