# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('lessons', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='lessons.lesson', verbose_name='lesson'),
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(blank=True, help_text='The person who goes in the water. Required for lessons.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='students.student', verbose_name='student'),
        ),
    ]
