# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('customers', '0001_initial'),
        ('lessons', '0001_initial'),
        ('students', '0001_initial'),
        ('surf_camps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='surf_camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='surf_camps.surfcamp', verbose_name='surf camp'),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='converted_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_conversions', to='bookings.booking', verbose_name='resulting booking'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='customers.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='lessons.lesson', verbose_name='lesson'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='students.student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='surf_camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='surf_camps.surfcamp', verbose_name='surf camp'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'booked_at'], name='bookings_bo_status_550fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='bookings_bo_custome_0cbf77_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['lesson', 'status'], name='bookings_bo_lesson__3d1600_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status', 'status'], name='bookings_bo_payment_f398ba_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['lesson', 'is_converted', 'position'], name='bookings_wa_lesson__898406_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['surf_camp', 'is_converted', 'position'], name='bookings_wa_surf_ca_fd2979_idx'),
        ),
    ]
