# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('metric_key', models.CharField(db_index=True, help_text='Dotted identifier of the measure, e.g. revenue.total or bookings.cancellation_rate.', max_length=100, verbose_name='metric')),
                ('period_start', models.DateField(db_index=True, verbose_name='period start')),
                ('period_end', models.DateField(help_text='Inclusive last day of the measured window.', verbose_name='period end')),
                ('granularity', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], db_index=True, default='day', max_length=5, verbose_name='granularity')),
                ('value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Money, a rate or a duration — the metric decides the unit.', max_digits=14, verbose_name='value')),
                ('count', models.PositiveIntegerField(default=0, help_text='How many source rows the value was computed from.', verbose_name='record count')),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='Optional breakdown the value is sliced by, e.g. {"lesson_type": "group-beginner"}.', verbose_name='dimensions')),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='computed at')),
            ],
            options={
                'verbose_name': 'metric snapshot',
                'verbose_name_plural': 'metric snapshots',
                'ordering': ['-period_start', 'metric_key'],
                'indexes': [models.Index(fields=['metric_key', 'granularity', 'period_start'], name='analytics_m_metric__f9bfaf_idx'), models.Index(fields=['metric_key', '-computed_at'], name='analytics_m_metric__3512e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('metric_key', 'period_start', 'period_end', 'granularity'), name='uniq_metric_snapshot_window'), models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='metric_snapshot_period_ordered')],
            },
        ),
    ]
