# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('equipment', '0001_initial'),
        ('instructors', '0001_initial'),
        ('locations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(choices=[('first_surf', 'First surf experience'), ('beginner', 'Beginner lesson'), ('intermediate', 'Intermediate lesson'), ('advanced_coaching', 'Advanced coaching'), ('private', 'Private lesson'), ('group', 'Group lesson'), ('kids', 'Kids lesson'), ('competition', 'Competition training'), ('video_analysis', 'Video analysis'), ('camp_training', 'Surf camp training')], db_index=True, default='group', max_length=20, verbose_name='category')),
                ('min_level', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], default='first_time', max_length=20, verbose_name='minimum level')),
                ('max_level', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], default='beginner', help_text='The hardest level taught. It also sets the safety ratio.', max_length=20, verbose_name='maximum level')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, help_text='Leave empty for no lower limit.', null=True, verbose_name='minimum age')),
                ('max_age', models.PositiveSmallIntegerField(blank=True, help_text='Leave empty for no upper limit.', null=True, verbose_name='maximum age')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MinValueValidator(15)], verbose_name='duration (minutes)')),
                ('max_students', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='maximum students')),
                ('min_students', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='minimum students')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='base price')),
                ('price_per_extra_student', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Charged for every participant above the minimum group size.', max_digits=12, verbose_name='price per extra student')),
                ('requires_board', models.BooleanField(default=True, verbose_name='requires a board')),
                ('requires_wetsuit', models.BooleanField(default=True, verbose_name='requires a wetsuit')),
                ('requires_leash', models.BooleanField(default=True, verbose_name='requires a leash')),
                ('colour', models.CharField(default='#0ea5e9', help_text='Hexadecimal colour used on the lesson calendar.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hexadecimal colour such as #0ea5e9.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='calendar colour')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='sort order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'lesson type',
                'verbose_name_plural': 'lesson types',
                'ordering': ['sort_order', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('lesson_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='lesson code')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('capacity', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacity')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed — conditions')], db_index=True, default='scheduled', max_length=20, verbose_name='status')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, default=None, help_text="Leave empty to use the lesson type's base price.", max_digits=12, null=True, verbose_name='price override')),
                ('notes', models.TextField(blank=True, help_text='Visible to customers.', verbose_name='notes')),
                ('internal_notes', models.TextField(blank=True, help_text='Never shown to customers.', verbose_name='internal notes')),
                ('conditions_snapshot', models.JSONField(blank=True, default=dict, help_text='Conditions frozen at lesson time. Legal evidence — never recomputed.', verbose_name='surf conditions snapshot')),
                ('safety_briefing_done', models.BooleanField(default=False, verbose_name='safety briefing delivered')),
                ('safety_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='safety checked at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('assistant_instructors', models.ManyToManyField(blank=True, related_name='assisted_lessons', to='instructors.instructor', verbose_name='assistant instructors')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='instructors.instructor', verbose_name='instructor')),
                ('safety_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_checked_lessons', to=settings.AUTH_USER_MODEL, verbose_name='safety checked by')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='locations.surfspot', verbose_name='surf spot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='lessons.lessontype', verbose_name='lesson type')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ['-date', 'start_time'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('checked_in', 'Checked in'), ('attended', 'Attended'), ('no_show', 'No show'), ('cancelled', 'Cancelled')], db_index=True, default='registered', max_length=20, verbose_name='status')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='checked in at')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='How the student rated the lesson, 1 to 5.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='student rating')),
                ('student_feedback', models.TextField(blank=True, verbose_name='student feedback')),
                ('instructor_notes', models.TextField(blank=True, verbose_name='instructor notes')),
                ('assigned_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_assignments', to='equipment.equipment', verbose_name='assigned board')),
                ('assigned_wetsuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wetsuit_assignments', to='equipment.equipment', verbose_name='assigned wetsuit')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='bookings.booking', verbose_name='booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='lessons.lesson', verbose_name='lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_attendances', to='students.student', verbose_name='student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'lesson attendance',
                'verbose_name_plural': 'lesson attendances',
                'ordering': ['lesson', 'student'],
                'indexes': [models.Index(fields=['lesson', 'status'], name='lessons_les_lesson__7948d1_idx'), models.Index(fields=['student', 'status'], name='lessons_les_student_6bc283_idx')],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'student'), name='lessons_attendance_unique_student')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='lessontype',
            index=models.Index(fields=['is_active', 'sort_order'], name='lessons_les_is_acti_947162_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['date', 'status'], name='lessons_les_date_d2c7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['instructor', 'date'], name='lessons_les_instruc_1af076_idx'),
        ),
    ]
