# Generated by Django 5.2.17 on 2026-08-17 22:32

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.SlugField(help_text='Stable identifier used by imports and integrations, e.g. wax.', max_length=40, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('icon', models.CharField(default='package', help_text='Name of a vendored Lucide icon, e.g. shopping-cart.', max_length=40, verbose_name='icon')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first on the terminal tab strip.', verbose_name='sort order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='pos.productcategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('sku', models.CharField(help_text='Internal article number. Printed on the shelf label.', max_length=40, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='EAN / UPC as printed on the packaging. Scanned at the till.', max_length=64, verbose_name='barcode')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='What the school pays the supplier, per unit.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='cost price')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shelf price, tax included — exactly what the customer pays.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='sale price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Share of the shelf price that is tax. 0 for exempt goods.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='tax rate (%)')),
                ('stock_quantity', models.IntegerField(db_index=True, default=0, help_text='Derived from the stock ledger — never edit it directly.', verbose_name='stock on hand')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='At or below this level the product is flagged for reordering.', verbose_name='reorder point')),
                ('track_stock', models.BooleanField(default=True, help_text='Turn off for services and made-to-order items with no shelf count.', verbose_name='track stock')),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('pair', 'Pair'), ('set', 'Set'), ('litre', 'Litre'), ('kg', 'Kilogram')], db_index=True, default='piece', max_length=10, verbose_name='unit')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pos/products/%Y/%m/', validators=[apps.core.validators.validate_image_upload], verbose_name='photo')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='supplier')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first in the terminal grid.', verbose_name='sort order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pos.productcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['sort_order', 'name'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('sale_number', models.CharField(blank=True, help_text='Generated automatically, e.g. S-000001.', max_length=20, unique=True, verbose_name='receipt number')),
                ('sold_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='sold at')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='discount')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='discount (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax already contained in the total — not added to it.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='tax included')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='tendered')),
                ('change_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='change given')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit / debit card'), ('transfer', 'Bank transfer'), ('online', 'Online payment'), ('package', 'Lesson package'), ('voucher', 'Voucher'), ('other', 'Other')], db_index=True, default='cash', max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('voided', 'Voided'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=15, verbose_name='status')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='voided at')),
                ('void_reason', models.TextField(blank=True, verbose_name='void reason')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='cashier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(blank=True, help_text='Optional — walk-in sales stay anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer', verbose_name='customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
                'ordering': ['-sold_at', '-id'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shelf price at the moment of sale, tax included.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='unit price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='line discount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='tax included')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='line total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='pos.product', verbose_name='product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.sale', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'sale item',
                'verbose_name_plural': 'sale items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase received'), ('sale', 'Sold'), ('return', 'Returned to stock'), ('adjustment', 'Stock take adjustment'), ('damage', 'Damaged / written off'), ('transfer', 'Transfer'), ('initial', 'Opening balance')], db_index=True, default='adjustment', max_length=15, verbose_name='movement')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Signed: negative when stock leaves the shelf.', max_digits=8, verbose_name='quantity')),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='balance after')),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Receipt number, supplier invoice or stock-take reference.', max_length=80, verbose_name='reference')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pos.product', verbose_name='product')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='pos.sale', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent', 'sort_order'], name='pos_cat_parent_order'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active', 'sort_order'], name='pos_cat_active_order'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category'], name='pos_prod_active_cat'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'sort_order'], name='pos_prod_active_order'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['track_stock', 'stock_quantity'], name='pos_prod_stock'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('barcode', ''), _negated=True)), fields=('barcode',), name='pos_product_unique_barcode'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'sold_at'], name='pos_sale_status_date'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cashier', 'sold_at'], name='pos_sale_cashier_date'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', 'sold_at'], name='pos_sale_customer_date'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='pos_item_sale_product'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='pos_item_product'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-created_at'], name='pos_move_product_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='pos_move_type_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['sale'], name='pos_move_sale'),
        ),
    ]
