# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('recorded_at', models.DateTimeField(db_index=True, help_text='The moment these conditions describe.', verbose_name='recorded at')),
                ('is_forecast', models.BooleanField(db_index=True, default=False, help_text='A modelled future hour rather than an observation of now.', verbose_name='forecast')),
                ('source', models.CharField(choices=[('provider', 'Weather provider'), ('manual', 'Entered by staff'), ('import', 'Imported')], db_index=True, default='provider', max_length=20, verbose_name='source')),
                ('provider', models.CharField(blank=True, db_index=True, help_text='Identifier of the data source, e.g. open-meteo.', max_length=40, verbose_name='provider')),
                ('wave_height_m', models.FloatField(blank=True, null=True, verbose_name='wave height (m)')),
                ('wave_period_s', models.FloatField(blank=True, null=True, verbose_name='wave period (s)')),
                ('wave_direction_deg', models.FloatField(blank=True, null=True, verbose_name='wave direction (°)')),
                ('swell_height_m', models.FloatField(blank=True, null=True, verbose_name='swell height (m)')),
                ('swell_period_s', models.FloatField(blank=True, null=True, verbose_name='swell period (s)')),
                ('swell_direction_deg', models.FloatField(blank=True, null=True, verbose_name='swell direction (°)')),
                ('wind_wave_height_m', models.FloatField(blank=True, null=True, verbose_name='wind wave height (m)')),
                ('wind_speed_kmh', models.FloatField(blank=True, null=True, verbose_name='wind speed (km/h)')),
                ('wind_gust_kmh', models.FloatField(blank=True, null=True, verbose_name='wind gusts (km/h)')),
                ('wind_direction_deg', models.FloatField(blank=True, null=True, verbose_name='wind direction (°)')),
                ('wind_type', models.CharField(blank=True, choices=[('offshore', 'Offshore'), ('cross_offshore', 'Cross-offshore'), ('cross_shore', 'Cross-shore'), ('cross_onshore', 'Cross-onshore'), ('onshore', 'Onshore'), ('glassy', 'Glassy / no wind')], db_index=True, help_text="Classified against the spot's beach orientation.", max_length=20, verbose_name='wind type')),
                ('sea_level_height_msl_m', models.FloatField(blank=True, null=True, verbose_name='sea level above MSL (m)')),
                ('tide_state', models.CharField(choices=[('low', 'Low tide'), ('mid_rising', 'Mid — rising'), ('high', 'High tide'), ('mid_falling', 'Mid — falling'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Derived from the modelled sea level — not a tide-station reading.', max_length=15, verbose_name='tide')),
                ('air_temperature_c', models.FloatField(blank=True, null=True, verbose_name='air temperature (°C)')),
                ('water_temperature_c', models.FloatField(blank=True, null=True, verbose_name='water temperature (°C)')),
                ('weather_code', models.IntegerField(blank=True, help_text='WMO 4677 present-weather code.', null=True, verbose_name='weather code')),
                ('weather_description', models.CharField(blank=True, max_length=120, verbose_name='weather')),
                ('uv_index', models.FloatField(blank=True, null=True, verbose_name='UV index')),
                ('precipitation_mm', models.FloatField(blank=True, null=True, verbose_name='precipitation (mm)')),
                ('cloud_cover_pct', models.FloatField(blank=True, null=True, verbose_name='cloud cover (%)')),
                ('visibility_km', models.FloatField(blank=True, null=True, verbose_name='visibility (km)')),
                ('sunrise', models.DateTimeField(blank=True, null=True, verbose_name='sunrise')),
                ('sunset', models.DateTimeField(blank=True, null=True, verbose_name='sunset')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text="The provider's response, kept so a past decision can be audited.", verbose_name='provider payload')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='locations.surfspot', verbose_name='surf spot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'surf condition',
                'verbose_name_plural': 'surf conditions',
                'ordering': ['-recorded_at', 'spot__name'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SurfScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('level', models.CharField(choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], db_index=True, max_length=20, verbose_name='surf level')),
                ('score', models.PositiveSmallIntegerField(help_text='0-100. Computed from measured values, not generated by AI.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='score')),
                ('factors', models.JSONField(blank=True, default=list, help_text='The weighted components behind the score, for the explanation panel.', verbose_name='factors')),
                ('recommendation', models.TextField(blank=True, verbose_name='recommendation')),
                ('is_safe_for_level', models.BooleanField(db_index=True, default=True, help_text='False when wave height or wind exceeds the hard limit for this level.', verbose_name='safe for this level')),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Always False for the computed score. AI never sets the number.', verbose_name='AI generated')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='surf_conditions.surfcondition', verbose_name='condition')),
            ],
            options={
                'verbose_name': 'surf score',
                'verbose_name_plural': 'surf scores',
                'ordering': ['condition', 'level'],
            },
        ),
        migrations.CreateModel(
            name='ConditionForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='generated at')),
                ('summary', models.JSONField(blank=True, default=dict, help_text="The hourly series and the day's aggregates, ready for the chart.", verbose_name='summary')),
                ('best_window_start', models.TimeField(blank=True, null=True, verbose_name='best window from')),
                ('best_window_end', models.TimeField(blank=True, null=True, verbose_name='best window to')),
                ('best_level', models.CharField(blank=True, choices=[('first_time', 'First Time'), ('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], help_text='The level this day scores highest for. Blank when no wave data exists.', max_length=20, verbose_name='best suited level')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_forecasts', to='locations.surfspot', verbose_name='surf spot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'condition forecast',
                'verbose_name_plural': 'condition forecasts',
                'ordering': ['spot__name', 'date'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['spot', 'date'], name='sc_fc_spot_date')],
                'constraints': [models.UniqueConstraint(fields=('spot', 'date'), name='sc_fc_unique_spot_day')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='surfcondition',
            index=models.Index(fields=['spot', '-recorded_at'], name='sc_cond_spot_recorded'),
        ),
        migrations.AddIndex(
            model_name='surfcondition',
            index=models.Index(fields=['spot', 'is_forecast', 'recorded_at'], name='sc_cond_spot_fc'),
        ),
        migrations.AddConstraint(
            model_name='surfcondition',
            constraint=models.UniqueConstraint(fields=('spot', 'recorded_at', 'is_forecast'), name='sc_cond_unique_reading'),
        ),
        migrations.AddIndex(
            model_name='surfscore',
            index=models.Index(fields=['level', '-score'], name='sc_score_level_value'),
        ),
        migrations.AddConstraint(
            model_name='surfscore',
            constraint=models.UniqueConstraint(fields=('condition', 'level'), name='sc_score_unique_level'),
        ),
    ]
