# Generated by Django 5.2.17 on 2026-08-17 22:32

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.SlugField(help_text='Stable identifier used by the code, e.g. "booking-confirmed".', max_length=80, unique=True, verbose_name='code')),
                ('category', models.CharField(choices=[('lesson_reminder', 'Lesson reminder'), ('booking', 'Booking'), ('payment', 'Payment'), ('rental_overdue', 'Overdue rental'), ('equipment', 'Equipment'), ('maintenance', 'Maintenance'), ('weather', 'Weather'), ('safety', 'Safety'), ('backup', 'Backup'), ('system', 'System'), ('ai', 'AI assistant'), ('crm', 'CRM')], db_index=True, default='system', max_length=20, verbose_name='category')),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10, verbose_name='level')),
                ('title_en', models.CharField(max_length=200, verbose_name='title (EN)')),
                ('title_tr', models.CharField(blank=True, max_length=200, verbose_name='title (TR)')),
                ('body_en', models.TextField(blank=True, verbose_name='message (EN)')),
                ('body_tr', models.TextField(blank=True, verbose_name='message (TR)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'notification template',
                'verbose_name_plural': 'notification templates',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Turn off to stop new entries appearing in the bell menu.', verbose_name='in-app notifications')),
                ('email_enabled', models.BooleanField(default=True, help_text='Warnings and errors are also sent to your e-mail address.', verbose_name='e-mail notifications')),
                ('categories_muted', models.JSONField(blank=True, default=list, help_text='Categories you never want to hear about, on any channel.', verbose_name='muted categories')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='No e-mail is sent between these two times. In-app entries still arrive.', null=True, verbose_name='quiet hours start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='quiet hours end')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('category', models.CharField(choices=[('lesson_reminder', 'Lesson reminder'), ('booking', 'Booking'), ('payment', 'Payment'), ('rental_overdue', 'Overdue rental'), ('equipment', 'Equipment'), ('maintenance', 'Maintenance'), ('weather', 'Weather'), ('safety', 'Safety'), ('backup', 'Backup'), ('system', 'System'), ('ai', 'AI assistant'), ('crm', 'CRM')], db_index=True, default='system', max_length=20, verbose_name='category')),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=10, verbose_name='level')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='message')),
                ('link_url', models.CharField(blank=True, help_text='Relative path opened when the notification is clicked.', max_length=500, verbose_name='link')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('is_emailed', models.BooleanField(default=False, verbose_name='e-mailed')),
                ('emailed_at', models.DateTimeField(blank=True, null=True, verbose_name='e-mailed at')),
                ('related_object_type', models.CharField(blank=True, help_text='Lowercase "app_label.model" label — deliberately not a foreign key.', max_length=100, verbose_name='related record type')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='related record id')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['category', '-created_at'], name='notificatio_categor_6dc2ff_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='notificatio_related_f82ec2_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
